### ISSUE TITLE
Cannot Proceed Past Step 1 of Checkout

### ISSUE THREAD

**Issue by caitlinmekita** [amzn/amazon-payments-magento-2-plugin#515] opened 2019-06-10 20:40 UTC
#### What I expected

After logging into Amazon and selecting the shipping address, select the "Next" button to proceed to the payment step of checkout before completing my order.

#### What happened instead

Nothing happens when I select the "Next" button. 

#### Steps to reproduce the issue

1. Choose a product, for example: https://staging.industrywest.com/coat-frame.html
2. Add the product to the cart
3. Proceed to the cart page
4. Select Amazon Pay button
5. Log in with *LIVE* Amazon account credentials
6. Try and proceed past the first step of checkout

**Note this issue is sometimes intermittent. If you cannot reproduce please try another browser such as Safari or on Incognito mode.

#### Your setup

* Magento version: 2.2.7
* Amazon Pay Extension Version: 1.2.8
* Magento Edition: Enterprise Cloud
* JavaScript Console: 

<img width="1413" alt="Screen Shot 2019-06-10 at 4 37 09 PM" src="https://user-images.githubusercontent.com/34772334/59225210-226a5b80-8b9e-11e9-850e-ff1a9535a038.png">

* Shop URL : staging.industrywest.com

**Comment by lemked** [comment] 2019-06-12 06:17
Hi @caitlinmekita ,

I couldn't reproduce the issue as any item that I've tried was out of stock.

Before investigating further, can you please update the version of our extension to 2.1.2? This is the version that should usually be shipped with Magento 2.2.7. The installation/update should be possible via the following composer command.

```
composer require amzn/amazon-payments-magento-2-plugin:2.1.2
php bin/magento setup:upgrade
php bin/magento setup:di:compile
```

Let me know if that solves the issue for you.

Kind regards,
Daniel

**Comment by caitlinmekita** [comment] 2019-06-12 13:54
Hi Daniel, thanks. 

Here are more products: https://staging.industrywest.com/home-decor-landing/home-decor/storage-accessories.html

This one specifically is definitely in stock: https://staging.industrywest.com/edgar-shelfs.html

We will also try upgrading and report back if there are issues.

**Comment by caitlinmekita** [comment] 2019-06-12 17:56
@lemked  I also want to make a correction - we're on 2.1.17 not 2.2.7

Regardless we'll still go ahead and upgrade the module.

**Comment by lemked** [comment] 2019-06-13 07:04
Hi @caitlinmekita ,

If you are using 2.1.17, version 1.2.8 is the latest compatible version that you should use. Please refer to our [README](https://github.com/amzn/amazon-payments-magento-2-plugin#branch-information) for version constraints and compatibilities.

On the staging site, I'm currently blocked by the following error. Selected address is one in Seattle.
![image](https://user-images.githubusercontent.com/4786477/59410881-41ddd000-8dba-11e9-8709-8b580e92c106.png)

Kind regards,
Daniel

**Comment by caitlinmekita** [comment] 2019-06-13 16:48
@lemked thanks -- haven't seen that issue before, are you using a real shipping address?

I've also just enabled free shipping so you should get a method now. Can you try again and let us know if you're able to reproduce now? Thanks!

**Comment by lemked** [comment] 2019-06-18 08:26
Thanks @caitlinmekita , I can now reproduce this issue. Can you switch the theme to the default theme Luna to see whether the problem persists?

Regarding the address: I've been using an address in Seattle.

**Comment by lemked** [comment] 2019-07-11 15:00
Hi @caitlinmekita ,

Did you have a chance to check whether the problem persists with the default theme?

**Comment by subbu1993** [comment] 2019-09-13 12:10
Hey @lemked 

I have more details to add to this

1) The issue happens only the first time the checkout page is loaded with amazon pay selected (reloading the checkout page/ going back and proceeding to checkout again has no issues)
2) The issue on the first time is that the call `shippingAddress.data.validate` sets `params.invalid` to `false` https://github.com/magento/magento2/blob/2.1/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L276
3) On subsequent attempts I am not sure why, but the calls to the same method sets `params.invalid` to `true`
4) In my debugging the `setShippingInformation` method from the shipping.js file of the amazon pay module is never called, I also confirmed that the file itself does not load in the network tab

Have you seen this happening in any of your tests ?

**Comment by lemked** [comment] 2019-09-16 13:41
Hi @subbu1993 ,

I can't recall having seen this specific problem before. As we don't actively maintain the 1.x branch of our extension anymore, it might be a problem that has been fixed in a more recent version already.

Would it be possible for you to update to Magento 2.2 or 2.3 to see whether the problem persists?

Kind regards,
Daniel

**Comment by balibani** [comment] 2019-09-19 14:32
@subbu1993  @lemked  This issue is caused due to ShipperHQ's shipping.js overriding Amazon Pay extension's Shipping.js . This prevents the checkout from bypassing shipping validation, which isn't required for Amazon Pay's Shipping Widget. The solution would be to either force the shipperHQ integration to use Amazon Pay's shipping.js or copy Amazon Pay Shipping.js content into ShipperHQ's Shipping.js  ( make this conditional for amazon pay payment method only using quote.paymentMethod() to read the value) .

**Closed** 2020-01-27 17:01 UTC
Labels: customer feedback required
