### ISSUE TITLE
Amazon Pay directs to initial checkout page without client info

### ISSUE THREAD

**Issue by kevlor** [amzn/amazon-payments-magento-2-plugin#152] opened 2017-10-25 15:28 UTC
Amazon Pay 1.2.0 was installed on my magento 2.1.7 store.

When someone clicks on the Amazon Pay button in the cart it opens a box to login to Amazon and share the information with my store.

Then it is supposed to show a box in checkout with the name and address(es) of client and pick shipping type to continue.
Two things that are happening:

1) If a client already as registered on my website previously, the above process of checking out using Amazon Pay works great.

2) If it is a first time client, then instead of showing the box with the clients after (after authenticating with amazon), it goes to the first page of checkout for a client to fill out everything and the choice for paying with amazon pay is no longer there.

Anyone know the solution for this? I could really use some help. Thank you!

My setup

* Magento version: 2.1.7
* Magento Edition: Community
* PHP version: 7.0

**Comment by danielneu** [comment] 2017-10-26 09:59
Hi @kevlor 

we have not experienced anything similar so far.
Are you using any additional checkout extensions?

Best wishes 
Daniel

**Comment by kevlor** [comment] 2017-10-26 12:52
Hi Daniel,

No I am not. And I decided yesterday to install another magento store on the same server and install the amazon pay and worked fine. So clearly there is something conflicting in my store. I just can't figure out what it is.

Thanks,
John

**Comment by kevlor** [comment] 2017-10-28 14:25
Daniel,

Found the issue. Cannot have "Show date of birth" required in magento.
In other words cannot require a customer to enter DOB at checkout in magento, to work with the amazon pay extension.

Thank you,
John

**Comment by danielneu** [comment] 2017-10-30 08:58
Thanks for letting us know,

will hand this over to our experts.

Best wishes 
Daniel

**Comment by Vinod-1989** [comment] 2017-11-26 19:42
Hi @kevlor , 

We are also facing similar issue, any expected date to resolve this. Or any hard code change you can suggest us to resolve this thing. 


Thanks,
Vinod

**Comment by kevlor** [comment] 2017-11-27 10:32
Hello @Vinod-1989
We did not find a solution, other than just not requiring for the customer to enter DOB (date of birth).

Regards,
Kevlor

**Comment by islandskater43** [comment] 2018-02-10 08:34
Reproducible in M 2.2.2 w/ extension ver 1.2.4 by requiring DOB. 

Can be seen here: https://ec2-54-245-183-222.us-west-2.compute.amazonaws.com/

@danielneu - Do you feel this is an extension issue? I feel like this is simply M2 behavior.

**Comment by danielneu** [comment] 2018-02-12 11:28
@islandskater43 we have a ticket for this internally (13396).

Looking at the problem description above (2.), I feel the extension shoudl ask for the DOB, if required, and then continue with the Amazon Pay checkout.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2018-02-20 14:06
Hi,

we had new information on this issue.
This seems to be related to Magento 2 core issues, e.g.:

https://github.com/magento/magento2/issues/10489
https://github.com/magento/magento2/issues/3457

This happens, when a tleast one of the fields VAT, DoB or Gender are made required.

We will check with Magento on plans to fix this on their side and then decide if there is an action needed or even possible on our side.

Best wishes 
Daniel

**Comment by RayAnaya** [comment] 2020-01-25 02:35
I am going to go ahead and close this issue for now, as there have been a number of new releases both for Magento 2 and for Amazon Pay's Plugin.  If you continue to observe this issue in the latest versions of both, please feel free to re-open this issue.

**Closed by RayAnaya** 2020-01-25 02:35 UTC
Labels: ack, bug
