### ISSUE TITLE
IPN URL rendering in backoffice breaks Store Config when Admin GWS is enabled

### ISSUE THREAD

**Issue by barbazul** [amzn/amazon-payments-magento-2-plugin#1098] opened 2022-01-12 21:17 UTC
#### What I expected

The Payment Methods screen should work normally when a user limited to a single scope navigates to it

#### What happened instead

In production mode users only see a whte screen due to a fatal error.

The error is: `Uncaught exception 'Error' with message 'Call to a member function getBaseUrl() on null' in /vendor/amzn/amazon-pay-and-login-with-amazon-core-module/Block/Adminhtml/Form/Field/IpnUrl.php:36`

(line number changes with different versions)

#### Steps to reproduce the issue

1. Have more than one website enabled
2. Create a User profile for which you associate only one website scope
3. Login with an admin user with the limited profile
4. Navigate to Stores -> Configuration -> Sales -> Payment Methods

#### Your setup

* Magento version: 2.3.5-p1 - 2.4.3 (haven't tested any earlier versions)
* Amazon Pay Extension Version: >=3.4.1-p2  (haven't tested any earlier versions)
* Magento Edition: Enterprise / Enterprise Cloud
* JavaScript Console: N/A
* Shop URL : N/A

**Comment by barbazul** [comment] 2022-01-12 21:43
My own research lead me to the following conclusions:

* The line with the error is: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/Block/Adminhtml/System/Config/Form/IpnUrl.php#L35
* That line calls this method https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/StoreManagerInterface.php#L94-L99 which may return either a Store object or NULL. Current code assumes `$store` is always a store object.
* Implementation confirms the above: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/StoreManager.php#L254
* `magento/module-admin-gws` defines some plugins that would filter out websites and store groups based on role scopes which would trigger the condition in StoreManager that returns a NULL instead of a store object

For the time being I am patching this  module to return "You do not have permission to view this setting."  whenever `$store` is null. 

If there is interest, I can make a pull request out of it.

**Comment by sgabhart22** [comment] 2022-01-13 14:18
Hello @barbazul ,

Thank you for the detailed information and digging into this issue a little further! I have confirmed this is still present in the Marketplace version of the module as well.

I think the PR you've provided is a fine fix, but I'd like to confirm there isn't a case where we would still want to allow configuration changes for an admin who doesn't have default store view access.

**Comment by barbazul** [comment] 2022-01-15 23:29
My PR does not prevent a user with limited scope access from making changes, it just fails to print the IPN url for that user.

![Configuration-Settings-Stores-Magento-Admin](https://user-images.githubusercontent.com/240373/149640986-cac805f0-3927-4b6c-bb5b-6a8fa5c9047c.png)

**Comment by sgabhart22** [comment] 2022-01-18 13:47
Oh, right you are @barbazul ! My apologies, this fix seems to be working just fine. I'll request another review, and if we don't directly merge your PR, we will likely include the fix in an upcoming release crediting your work. Thanks again!

**Comment by sgabhart22** [comment] 2022-01-18 19:22
@barbazul I cherry picked your commit into a new branch of our repo, and also added a small message to display for the IPN URL value. You can view the PR here: https://github.com/BearGroup/amazon-payments-magento-2-plugin/pull/33

I'm going to close the PR you created for now, and once we merge and release the PR I linked (hopefully within the next week or so), I'll go ahead and close this issue. Let me know if you have any questions, and once again, we appreciate the contribution!

**Comment by christianzichichi** [comment] 2022-02-01 08:56
Hi @barbazul ,
the new release contains a fix for this issue: https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/5.10.0
Thanks a lot for your contribution
Best
Christian

**Closed by christianzichichi** 2022-02-01 08:56 UTC
