### ISSUE TITLE
Disabling Amazon Pay for website breaks its Checkout

### ISSUE THREAD

**Issue by sshymko** [amzn/amazon-payments-magento-2-plugin#209] opened 2018-03-16 21:29 UTC
#### What I expected

Amazon Pay payment method can be configured and enabled for one website, but kept disabled for other websites running on the same Magento instance.

#### What happened instead

Amazon Pay breaks the checkout of the website the payment method is disabled for.
Numerous JavaScript errors are displayed in the Console:
<img width="653" alt="cmg_magento_checkout_amazonpay_disabled_js_errors" src="https://user-images.githubusercontent.com/1231423/37545570-789a9e24-2926-11e8-9480-6a8b8197610f.png">

#### Steps to reproduce the issue

1. Create Website 1 and Website 2 in
Stores > Settings > All Stores > Create Website
2. Go to the payment methods configuration
Stores > Settings > Configuration > Sales > Payment Methods > Amazon Pay
3. Switch scope to Website 1
4. Configure Amazon Pay and ENABLE it
3. Switch scope to Website 2
4. Configure Amazon Pay but keep it DISABLED
5. Flush the configuration cache for the changes to take effect
6. Go to the frontend of the Website 2
7. Proceed to checkout

#### Your setup

* Magento version: 2.1.9
* Amazon Pay Extension Version: 1.2.5
* Magento Edition: Community
* Shop URL : https://cc.cmgdev.com/

**Comment by lemked** [comment] 2018-03-19 06:38
Probable duplicate of #207

**Comment by prayagr** [comment] 2018-09-26 20:07
The issue has been resolved, please reopen in case issue persists

**Closed by prayagr** 2018-09-26 20:07 UTC
Labels: duplicate
