### ISSUE TITLE
Call to a member function getAmazonOrderReferenceId() on null

### ISSUE THREAD

**Issue by stkrelax** [amzn/amazon-payments-magento-2-plugin#764] opened 2020-06-23 08:37 UTC
It checks if AmazonOrderReferenceId extensionattribute isset before trying to use it.

#### What happened instead

No Check, so Failure as in title of issue

#### Steps to reproduce the issue

no steps just the sourecode line were it happens

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/a3de39139f8b921d611f1b6071f200c6fbbc7d8c/src/Payment/Plugin/ConfirmOrderReference.php#L106

#### Your setup

* Magento version: 2.3.5-p1
* Amazon Pay Extension Version: 3.4.1
* Magento Edition: Community

**Comment by bear-ihor** [comment] 2020-06-24 00:33
Hi @stkrelax,

I couldn't reproduce the issue having a setup you described.
Does the issue occur for you permanently or sporadically?
Could the issue be caused by a 3rd party extension you haven't mentioned?

Though an additional check can be added at the code line, this doesn't seem to be enough.
The AmazonOrderReference must be set by the time the code line is called.
If it was not set, then the further payment processing is at risk.

Thank you.

**Comment by stkrelax** [comment] 2020-06-24 10:57
we are also using iways/paypal_plus_payment

thanks for the infos, we are monitoring this.

**Comment by stkrelax** [comment] 2020-07-01 07:40
Meanwhile in this 7 days after we fixed the Fatal Error, no other problems appeared. Just to inform you.

**Comment by christianzichichi** [comment] 2020-07-01 08:36
Hi @stkrelax,
that's very good to hear. May I ask how you fixed the error? If there's a bug in the code, we would like to fix it.

Thanks a lot
Regards

Christian

**Comment by stkrelax** [comment] 2020-07-01 10:40
@christianzichichi 
I created custom module that overwrites the class via di preference
and changed the mentioned line to this 

` if ($quoteExtensionAttributes && $quoteExtensionAttributes->getAmazonOrderReferenceId()) { `

**Comment by christianzichichi** [comment] 2020-07-01 16:21
Hi @stkrelax .
thanks for your contribution, we have merged the fix you suggested into the plugin. Could please share more details on how the issue was reproduced in your installation? Did the issue occur for you permanently or sporadically?

Thanks
Regards

Christian

**Comment by stkrelax** [comment] 2020-07-02 05:40
I was not able to reproduce the error. I just saw it and reacted as fast as possible. The Error occured directly after Upgrading from 2.3.3 to 2.3.5-p1

They appear very sporadically. 3 times in 12h

```
[23-Jun-2020 09:55:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAmazonOrderReferenceId() on null in /var/www/app/tags/0.0.184/vendor/amzn/amazon-pay-module/Plugin/ConfirmOrderReference.php:91
Stack trace:
#0 /var/www/app/tags/0.0.184/vendor/magento/framework/Interception/Interceptor.php(146): Amazon\Payment\Plugin\ConfirmOrderReference->afterSet(Object(Magento\Quote\Model\PaymentMethodManagement\Interceptor), '14968', 50066, Object(Magento\Quote\Model\Quote\Payment\Interc$
#1 /var/www/app/tags/0.0.184/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\PaymentMethodManagement\Interceptor->Magento\Framework\Interception\{closure}(50066, Object(Magento\Quote\Model\Quote\Payment\Interceptor))
#2 /var/www/app/tags/0.0.184/generated/code/Magento/Quote/Model/PaymentMethodManagement/Interceptor.php(26): Magento\Quote\Model\PaymentMethodManagement\Interceptor->___callPlugins('set', Array, Array)
#3 /var/www/app/tags/0.0.184/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(135): Mag in /var/www/app/tags/0.0.184/vendor/amzn/amazon-pay-module/Plugin/ConfirmOrderReference.php on line 91
```

**Comment by RayAnaya** [comment] 2020-08-11 19:46
Hey @stkrelax 

Thank you for your help in providing some details around this issue - it helped us tremendously in trying to hunt down the actual problem.  We've been able to dig a little deeper, and believe we've found one of (if not the primary) the root causes here.  Apparently, there were some cases where an address might -look- like it was selected in the address book widget, but required the customer to actually, manually, click on that address.  If not, there would be no address selected, which in turn would result in an error when trying to call getAmazonOrderReferenceId.  There was no logic in our plugin to detect and act upon those situations, so it'd just try to call operations on an OrderReferenceId that was in an invalid state.

To this end, we've added a check and surface a standard error message (customer facing) as part of our latest version, to try and catch that situation.  Please let us know if you see this issue creeping up again - either by re-opening this issue, or submitting a new one for us to investigate.

Thanks!

**Closed by RayAnaya** 2020-08-11 19:46 UTC
Labels: ack, needs investigation, ticket created

**Comment by stkrelax** [comment] 2020-08-12 10:44
Hello @RayAnaya , 

good that is was helpful. Thats the reason i created the issue. 

We actually had a problem with the preference we created to fix this later on: 

we upgraded to magento 2.3.5-p2 and changes from the patch ( i suppose patch https://support.magento.com/hc/en-us/articles/360042646332-Patch-for-Amazon-Pay-checkout-issue-in-Magento-2-3-5-p1
which we didn't apply in 2.3.5-p1) that were included didn't take affect because of our preference...

We discovered this and removed our preference. Until this "removement", order place action was only possible with refreshing on order submit page. 

Now no Fatal Error appear anymore and checkout works as expected... even though the bad coding is still present

```   
public function afterSet(
        PaymentMethodManagementInterface $subject,
        $result,
        $cartId,
        PaymentInterface $paymentMethod
    ) {
        if ($paymentMethod->getMethod() == GatewayConfig::CODE) {
            $quote = $this->quoteRepository->get($cartId);
            $quoteExtensionAttributes = $quote->getExtensionAttributes();
            if ($quoteExtensionAttributes) {
                $amazonOrderReferenceId = $quoteExtensionAttributes
                    ->getAmazonOrderReferenceId()
                    ->getAmazonOrderReferenceId();

                if (!$this->checkoutSession->getData('is_amazon_suspended')) {
                    $this->orderInformationManagement->saveOrderInformation($amazonOrderReferenceId);
                }

                if ($this->canConfirmOrderReference()) {
                    $this->orderInformationManagement->confirmOrderReference(
                        $amazonOrderReferenceId,
                        $quote->getStoreId()
                    );
                }
            }
        }

        return $result;
    }
```

still prefer this
https://github.com/amzn/amazon-payments-magento-2-plugin/issues/764#issuecomment-652341465
Version

**Comment by RayAnaya** [comment] 2020-08-12 15:07
Thanks @stkrelax.  We hear you!  The Magento 2.3.5 release was not what we expected (evidenced by our need for 2.3.5-p1 and 2.3.5-p2), but that is not an excuse - we will continue to do better.

We'll take a second look at improving our code and handling of this issue, as it's definitely a tricky one to reproduce.  We see this in mobile views as well, and have been trying to find all the possible causes. Reviewing your comment, I do see that our engineering team went in a different direction to fix it (though based on the solution you submitted) - but I'm curious what you meant by the 'bad coding is still present'?  Is it that we over-engineered the fix?

**Comment by stkrelax** [comment] 2020-08-13 08:17
@RayAnaya 

Yeah 2.3.5 was ... let's say "interresting" ;) ... no body is perfect ...
 
with bad coding style i mean:

As described in this method the return value can be the wanted Object or null
```
    /**
     * Retrieve existing extension attributes object or create a new one.
     *
     * @return \Magento\Quote\Api\Data\CartExtensionInterface|null
     */
    public function getExtensionAttributes();
```
so as a programmer you should check if it returns null or object to prevent Fatal Errors
as you did here :
```
            $quoteExtensionAttributes = $quote->getExtensionAttributes();
            if ($quoteExtensionAttributes) {
```

but at the moment you get the AmazonOrderReferenceId such a check is missing:
```
                $amazonOrderReferenceId = $quoteExtensionAttributes
                    ->getAmazonOrderReferenceId()
                    ->getAmazonOrderReferenceId();
```

even though its clearly stated it can/could be null

```
    /**
     * @return \Amazon\Payment\Api\Data\QuoteLinkInterface|null
     */
    public function getAmazonOrderReferenceId()
    {
        return $this->_get('amazon_order_reference_id');
    }
```
