### ISSUE TITLE
Update from 2.1.9 to 2.2.0

### ISSUE THREAD

**Issue by MoschenBayern** [amzn/amazon-payments-magento-2-plugin#149] opened 2017-10-18 13:13 UTC
Preconditions

Steps to reproduce

Web Setup Wizard
System Upgrade
Check readiness
Expected result

all Points should be green
Actual result

We found conflicting component dependencies. Hide detail
Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1

Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 requires magento/framework ^100.1.0 -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.2.0-rc20, 100.1.9].
Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
Can only install one of: magento/framework[101.0.0, 100.1.0].
Can only install one of: magento/framework[101.0.0, 100.1.1].
Can only install one of: magento/framework[101.0.0, 100.1.2].
Can only install one of: magento/framework[101.0.0, 100.1.3].
Can only install one of: magento/framework[101.0.0, 100.1.4].
Can only install one of: magento/framework[101.0.0, 100.1.5].
Can only install one of: magento/framework[101.0.0, 100.1.6].
Can only install one of: magento/framework[101.0.0, 100.1.7].
Can only install one of: magento/framework[101.0.0, 100.1.8].
Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
Can only install one of: magento/framework[101.0.0, 100.1.9].
magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
Installation request for amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 -> satisfiable by amzn/amazon-pay-and-login-with-amazon-core-module[1.1.4].
Can anyone help me pls. All other Updates from 2.1.7 to 2.1.8 or from 2.1.8 to 2.1.9 went without any problems

This is a Amazon-Pay error

**Comment by danielneu** [comment] 2017-10-18 13:31
Hi,

this is a duplicate of #133, closing it for this reason.

2.2 availability is given in the master branch. A new release will be cut hopefully tomorrow (version 1.2.0) which will be compatible with 2.2

Best wishes 
Daniel

**Closed by danielneu** 2017-10-18 13:31 UTC
Labels: duplicate

**Comment by erobotics** [comment] 2017-10-25 22:30
when are you going to release 1.2.0? I saw 1.1.1 is the current. Thanks.

**Comment by danielneu** [comment] 2017-10-26 09:55
Hi,

1.2.0 was released 7 days ago:
https://github.com/amzn/amazon-payments-magento-2-plugin/releases/tag/1.2.0

Best wishes 
Daniel
