### ISSUE TITLE
Missing province/region issue affecting merchants in France, Italy and Spain

### ISSUE THREAD

**Issue by bianchif** [amzn/amazon-payments-magento-2-plugin#242] opened 2018-06-05 15:15 UTC
As a merchant in France, Italy or Spain, I need the province as a mandatory field. If the province field is missing from the Amazon address, I would expect an error to be raised during the Amazon Pay checkout, asking the buyer to provide this additional input field, or have a logic that populates this field automatically without interrupting the workflow at the payment step. 

In case an address is missing a required field and the address is selected in the checkout, trying to complete the checkout, a generic error message is shown in the wallet widget page. Go through the Amazon Pay workflow, add a shipping address with no province, and try to complete the workflow to reproduce the issue.

The issue was solved in the Magento core and with the migration of the Amazon Pay plugin in-core, from Magento version 2.2.4. 

Some merchants affected by the issue are managed by an agency working on Magento 2.1.10, which cannot upgrade all Magento versions for this fix. 

Since the solution to the issue was probably released to the Magento core in version 2.2.4, it would be good to know what the fix was and if it can be "back-ported" to the previous versions of the core. 

#### Your setup

* Magento version: any version lower than 2.2.4
* Amazon Pay Extension Version: any version that is not in-core
* Magento Edition: Community or Enterprise

**Comment by lemked** [comment] 2018-07-13 11:56
Duplicate of #175

**Closed by lemked** 2018-07-13 11:56 UTC
Labels: duplicate, needs investigation
