### ISSUE TITLE
Tag 1.2.7 login throws a fatal error

### ISSUE THREAD

**Issue by qlhu** [amzn/amazon-payments-magento-2-plugin#343] opened 2018-09-03 08:16 UTC
#### What I expected
Amazon Check Out page shows once logged in with a valid Amazon account.

#### What happened instead
amazon/login/authorize/ throws errors below.
![amazon-login-php-error](https://user-images.githubusercontent.com/29137910/44974364-004e0800-af92-11e8-8a83-561256c1d70a.png)

#### Steps to reproduce the issue
1. Install [amazon-payments-magento-2-plugin 1.2.7](https://github.com/amzn/amazon-payments-magento-2-plugin/tree/1.2.7) by using composer like below.
`composer require amzn/amazon-payments-magento-2-plugin:^1.2.7`
2. Configure Amazon Payment in Admin and refresh cache.
3. Visit the frontend store and then add an item to cart.
4. Press Amazon Pay button from cart page.
5. Log in with a valid Amazon account.

#### Your setup

* Magento version: 2.2.3
* Amazon Pay Extension Version: 1.2.7
* Magento Edition: Community
* Shop URL : [https://cc.cmgdev.com](https://cc.cmgdev.com)

#### Narrow Down
The [Authorize.php](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/1.2.7/src/Login/Controller/Login/Authorize.php) references **Amazon\Core\Api\Data\AmazonCustomerInterface** which isn't available to [amazon-payments-magento-2-plugin 1.2.7](https://github.com/amzn/amazon-payments-magento-2-plugin/tree/1.2.7).

**Comment by prayagr** [comment] 2018-09-06 00:17
Hi @qlhu , taking a look into this. Will get back to you shortly.

**Comment by bexdoggett** [comment] 2018-09-06 10:58
Hi, I have the same issue on a 2.1.14 Magento site and had to revert to 1.2.6 of the amazon pay module to resolve it.

**Comment by prayagr** [comment] 2018-09-06 22:17
Hi @qlhu , @bexdoggett , we have provided a fix (#348) for this and it has been merged into the 1.x branch. Please update the library and confirm if the issue is resolved.

**Comment by qlhu** [comment] 2018-09-10 06:57
Hi @prayagr , login issue is fixed. Please close this issue. Than you for help.

**Comment by bexdoggett** [comment] 2018-09-10 09:31
Hi @prayagr, the login issue is fixed on 2.1.14 too, thank you for resolving this

**Comment by prayagr** [comment] 2018-09-10 16:02
Thanks for the updates @qlhu and @bexdoggett. I am closing this issue and this fix will be included in a new release.

**Closed by prayagr** 2018-09-10 16:02 UTC

**Comment by bexdoggett** [comment] 2018-09-12 07:42
@prayagr Thanks, do you know when the next release in planned for?

**Comment by prayagr** [comment] 2018-09-12 08:07
Hey @bexdoggett , as this is a fatal bug, we will cut a new release by end of this week, if not earlier.
