### ISSUE TITLE
No payment methods

### ISSUE THREAD

**Issue by MHEGERM** [amzn/amazon-payments-magento-2-plugin#22] opened 2016-12-23 07:51 UTC
Hello,

I have installed the module as specified and set up, in the backend as well as in the Sellercentral. If I now want to test in the sandbox mode, I get in the second step no way to select a payment type, only the message appears: No payment methods.
Payment with Amazon and login with Amazon is activated.

Can you help me here? Mr. Neu from Amazon has referred me directly to you.

A screenshot can be found here: [www.e-combuy.de/img/screenshots/amazon_payment_sandbox.jpg](http://www.e-combuy.de/img/screenshots/amazon_payment_sandbox.jpg)

Many thanks and best regards

Michael

**Comment by OnTapSupport** [comment] 2017-01-26 14:04
Hello Michael,

Thanks for the screenshot.

If this is still an issue, can you please provide a screenshot of Chrome's Console panel (https://developers.google.com/web/tools/chrome-devtools/#console_panel) when the checkout has loaded? We would like to see if there are any Javascript error messages showing.

Can you also confirm the exact version and Edition (Community/Enterprise) of Magento 2 that you are using?

Regards,
Support Team.

**Comment by MHEGERM** [comment] 2017-01-30 06:47
Hello,
The problem still exists. The screenshots I have attached:
[www.e-combuy.de/img/screenshots/console_first_step.jpg](http://www.e-combuy.de/img/screenshots/console_first_step.jpg)
[www.e-combuy.de/img/screenshots/console_second_step.jpg](http://www.e-combuy.de/img/screenshots/console_second_step.jpg)

Best regards

Michael

**Comment by markenwirt** [comment] 2017-03-17 14:55
Hey,
we can confirm the error with PayPal Plus from i-ways - the offical paypal-plugin.
Amazon by itself does work but if u active both modules only PayPal Plus work correctly.

The process if both are activated:
- login with amazon works
- confirm the shipping works
- paymentmethods - does not work. There are no paymentmethods, no iframe from amazon, no errors in the console - nothing.

Is there an easy workaround?

**Comment by danielneu** [comment] 2017-03-17 15:31
Thanks.
Also for providing the detailed information we were missing.
This could be the cause for #22

We will investigate this.

**Comment by danielneu** [comment] 2017-03-17 15:37
I think this is the bad guy: https://github.com/i-ways/magento2-paypal-plus/blob/master/view/frontend/web/js/view/payment/method-renderer/payment.js#L122

Looks like this will run infinite.

**Comment by markenwirt** [comment] 2017-03-20 10:04
Thanks for your idea, but no thats not the problem. I tried this before and now again, but during the amazon-checkout-process there is no PayPal-JS loaded. 

I think there is a problem with the PHP-Functions. I don't know the correct name of the function but there are maybe 1 or more functions that amazon and paypal try to overwrite and paypal always wins. ^^ But my knowledge about magento is not good enough to debug this. Maybe this helps for another idea?

**Comment by danielneu** [comment] 2017-03-20 10:10
Thanks,

I debugged this late on Friday as well and can confirm, this is not the reason for this.
I will give it a last try today, in parallel our supporting agency is working on it, this will be fixed, independent on my success or failure.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-03-21 08:50
Another merchant affected, also using iWays PayPal Plus module.
Closing #23 in favor of this ticket.

**Comment by MoschenBayern** [comment] 2017-03-30 08:26
Any news about the problem with iWays PayPal Plus?
Need to get the payment-methods working. How long will it take?

**Comment by markenwirt** [comment] 2017-03-30 08:46
I have no new information from iways. They said:
"We are working on the problem."

**Comment by danielneu** [comment] 2017-03-30 08:49
We have looked into it as well. I will try to get in touch with iways and offer our support to get those two modules compatible.

**Comment by markenwirt** [comment] 2017-04-18 07:53
Did u both find a timeline for fixing this problem? Thanks for your support already.

**Comment by danielneu** [comment] 2017-04-18 08:08
Hi,

I am in touch with iWays and they are working on it. 
First results seem to be promising - I can and will not communicate any timelines, though, as this is out of my control.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-05-09 12:49
Hello,

this incompatibility can be removed by installing the newest version of the i-ways Paypal Plus module.
https://github.com/i-ways/magento2-paypal-plus/releases/tag/v1.0.5 

Please follow the instructions given there for the update.

**Closed by danielneu** 2017-05-09 12:49 UTC
Labels: ack, bug
