### ISSUE TITLE
Weird bug when order total is $0.01

### ISSUE THREAD

**Issue by korostii** [amzn/amazon-payments-magento-2-plugin#65] opened 2017-05-30 13:04 UTC
Related: https://github.com/amzn/amazon-payments-magento-2-plugin/issues/42
It is a common practice to test payment methods in production via orders with small amounts. We attempted to make a purchase with grand total of 0.01 and got some unexpected results.

#### Steps to reproduce the issue
1. Have a product with price = 0.01
2. Enable free shipping
3. Attempt to checkout that product with free shipping using Amazon Pay

#### What I expected
Order is placed without any errors.

#### What happened instead
An error is shown to the customer: `An error occurred on the server. Please try to place the order again.`

`paywithamazon.log` contains the following information:
```
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>The Value '0.0099999999999998' is invalid for the Parameter 'Amount'</Message>
  </Error>

```

#### Your setup
* Magento version: 2.1.5
* Magento Edition: Community

#### Additional considerations: 
The field seems to be validated against [this type](https://pay.amazon.com/us/developer/documentation/apireference/201752720) on API side although documentation doesn't mention any relevant restrictions. 

I am not sure whether it's a maximum string length validation or the value cannot go below 0.01 or what-else. If it's the string length, the issue can probably be reproduced with different amounts as well, yet the fix should be fairly straightforward either way.

Total amount of $0.02 seems to pass through just fine though.

**Comment by danielneu** [comment] 2017-05-30 13:21
Hi,

thanks a lot for raising this. The minimal allowed value is in fact 0.01 in a given currency.
We will get this sorted.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-08-22 07:09
@korostii 

Sorry for this taking so long,

This was not reproducible on our side and might have to do with the way PHP does the rounding in different PHP versions.

Can you either share access to a system where this is happening or tell us a bit more about the system the shop is running on, like PHP version, OS, 32bit vs 64 bit, ...?

Thanks
Daniel

**Comment by korostii** [comment] 2017-08-22 09:50
Sure, no problem. Using 0.02 in the meantime is a good enough workaround for us.
Unfortunately, I am not at liberty to share access to the system, but I will provide some details.

Architecture: x86_64
System: SMP Debian 3.16.36-1+deb8u1
PHP 7.0.16-1~dotdeb+8.1, Zend Engine v3.0.0 with Zend OPcache v7.0.16-1~dotdeb+8.1

Also it seems that I've previously omitted a detail which might be of significance: I believe the product bought had larger price, and the total was reduced to $0.01 using a coupon code.

**Comment by pronto2000** [comment] 2017-08-25 12:09
@korostii I'm pretty sure that the coupon part is indeed what causes this problem. Could you please provide me some additional data: exact original product price, coupon information, related taxes ... i.e. those things that are used for price calculation? While it is not necessary to fix this issue, being able to reproduce the error consistently certainly helps.

**Comment by korostii** [comment] 2017-08-25 15:00
> exact original product price, coupon information, related taxes
No, unfortunately I wasn't the one checking out the actual order and the logs don't seem to contain such details. 
This other order total logged (presumably before applying coupon) is all I have:
```
<OrderTotal>
        <CurrencyCode>USD</CurrencyCode>
        <Amount>7.23</Amount>
      </OrderTotal>
```

**Comment by danielneu** [comment] 2017-09-05 07:25
Hi,

we are closing this one as not reproducible.
Thanks for filing this and all the help, but this seems to be related to either a third party extension or something else we are not able to reproduce using a vanilla Magento.

Best wishes 
Daniel

**Closed by danielneu** 2017-09-05 07:25 UTC
Labels: ack, bug
