### ISSUE TITLE
Question: Compatibility with Magento 2.3

### ISSUE THREAD

**Issue by Mandrino** [amzn/amazon-payments-magento-2-plugin#413] opened 2019-01-12 09:09 UTC
Hello,

when will the module be compatible with Magento 2.3? 
Also, when will you update the module on Magento marketplace?

Thanks

**Comment by lemked** [comment] 2019-01-14 07:53
Dear @Mandrino ,

The extension is already compatible to Magento 2.3 and is distributed as part of the Magento 2. After installation, you should find version 3.0.0 of the extension installed on your system. If this isn't the case, you should be able to install the extension via the following composer command:
`composer require amzn/amazon-pay-and-login-magento-2-module:3.0.0`

We didn't update the extension on the marketplace as the extension is distributed along with Magento 2 since Magento 2.2.4, but we will have a look into.

Kind regards,
Daniel

**Comment by erobotics** [comment] 2019-02-15 19:41
Stopped working recently tried to install 3.1.2 but failed

**Comment by lemked** [comment] 2019-02-18 08:18
Dear @erobotics ,

Can you please provide details on the issue that you have encountered (error message, screenshots, steps to reproduce)?

Kind regards,
Daniel

**Comment by erobotics** [comment] 2019-03-28 22:59
Tyring to upgrade to magento 2.3.1

  Problem 1
    - Can only install one of: amzn/amazon-pay-and-login-magento-2-module[3.1.4, 3.0.0].
    - Can only install one of: amzn/amazon-pay-and-login-magento-2-module[3.1.4, 3.0.0].
    - Can only install one of: amzn/amazon-pay-and-login-magento-2-module[3.0.0, 3.1.4].
    - magento/product-community-edition 2.3.1 requires amzn/amazon-pay-and-login-magento-2-module 3.1.4 -> satisfiable by amzn/amazon-pay-and-login-magento-2-module[3.1.4].
    - Installation request for magento/product-community-edition 2.3.1 -> satisfiable by magento/product-community-edition[2.3.1].
    - Installation request for amzn/amazon-pay-and-login-magento-2-module (locked at 3.0.0) -> satisfiable by amzn/amazon-pay-and-login-magento-2-module[3.0.0].

  Problem 1
    - The requested package amzn/amazon-payments-magento-2-plugin ^3.1.4 exists as amzn/amazon-payments-magento-2-plugin[1.0.1, 1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.x-dev, 2.0.14, 2.0.15, 2.0.16, 2.1.x-dev, 2.x-dev, dev-master] but these are rejected by your constraint.

**Comment by ThomasChoy** [comment] 2019-03-30 18:25
I also hit this issue when I try to upgrade from 2.3.0 to 2.3.1 by the following command:

`composer require magento/product-community-edition=2.3.1`

After some research I tried the following and this work for me:

`composer require amzn/amazon-pay-and-login-magento-2-module=3.0.0
composer require magento/product-community-edition=2.3.1 --no-update
composer require amzn/amazon-pay-and-login-magento-2-module=3.1.4 --no-update
composer update`

**Comment by lemked** [comment] 2019-04-04 07:06
When updating Magento 2, please be sure to carefully follow the instructions in the official documentation:
https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html

The key here is to run the update with the '--no-update' flag:
`composer require magento/product-community-edition=2.3.1 --no-update`

After this the actual update can be executed as below
`composer update`

Closing this issue. Please re-open if there are still issues with the update.

Kind regards,
Daniel

**Closed by lemked** 2019-04-04 07:06 UTC
Labels: customer feedback required, no issue

**Comment by erobotics** [comment] 2019-04-04 19:00
work like a charm! Thanks.

> I also hit this issue when I try to upgrade from 2.3.0 to 2.3.1 by the following command:
> 
> `composer require magento/product-community-edition=2.3.1`
> 
> After some research I tried the following and this work for me:
> 
> `composer require amzn/amazon-pay-and-login-magento-2-module=3.0.0`
> `composer require magento/product-community-edition=2.3.1 --no-update`
> `composer require amzn/amazon-pay-and-login-magento-2-module=3.1.4 --no-update`
> `composer update`
