### ISSUE TITLE
Failed to load the "Amazon_Login/js/view/login-button-wrapper" component

### ISSUE THREAD

**Issue by elfeffe** [amzn/amazon-payments-magento-2-plugin#608] opened 2020-03-02 12:13 UTC
#### What I expected

Load product page without any JS errors
#### What happened instead

I see that error
#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 3.3.1
* Magento Edition: Community 
* JavaScript Console: https://gyazo.com/8ef598138d1ef21ddbdd00090824f03b
* Shop URL :

**Comment by christianzichichi** [comment] 2020-03-02 13:20
Hi @elfeffe,

thanks for reporting the issue. We were already aware of it and a fix for it will be included in the next plugin release (possibly 3.4.2). I'll let you know as soon as it's ready. In the meantime, can you please tell us if that error for you causes also either the checkout or the login module not to work as expected? 

Thanks
Regards

Christian

**Comment by elfeffe** [comment] 2020-03-02 16:03
I don't know, because I didn't upload to live since I have that error.
Any idea about when will you publish the fix?

**Comment by christianzichichi** [comment] 2020-03-03 17:27
Hi @elfeffe,

the fix for this will be included in Magento 2.3.6 Release coming in July 2020, and in Amazon Pay plugin version 3.4.2 (still to be released). A patch in this case is not urgently required because that error is not affecting login and checkout functionalities, but you’ll find update instructions here for that version (or more up to date versions) once available: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD


Thanks for reporting the issue and your help in improving the module

Regards

Christian

**Closed by christianzichichi** 2020-03-03 17:27 UTC
Labels: ack, reproducible, waiting for release

**Comment by elfeffe** [comment] 2020-03-04 10:48
I'm also having this on the checkout page

Widgets.js?nomin:2 Uncaught TypeError: Cannot read property 'Login' of undefined
    at HTMLImageElement.W (Widgets.js?nomin:2)

https://static-na.payments-amazon.com/OffAmazonPayments/us/js/Widgets.js?nomin

**Comment by christianzichichi** [comment] 2020-03-04 11:57
Hi @elfeffe,
can you please send a console screenshot and a description on how to reproduce this new error at payments-cp-devel@amazon.com? Also, does it affect Login or checkout functionalities? We'll then let you know if that is related (and will also disappear in 2.3.6 release) or if it's a different issue that needs to be solved.

thanks
regards

Christian

**Comment by elfeffe** [comment] 2020-03-05 13:09
It has dissapeared, automagically...

**Comment by realadityayadav** [comment] 2020-04-19 15:51
@christianzichichi Can you share the fix against this please?

**Comment by christianzichichi** [comment] 2020-04-21 08:02
Hi @realadityayadav, please update your plugin to the latest release following one of the instructions in this link (based on your Magento installation): https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD

Thanks
Regards

Christian

**Comment by KevinOxwork** [comment] 2020-04-21 09:04
Hi @christianzichichi ,

I have the same problem with js error and have a question about the patch. I already applied one and have that line in my composer :

`"amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.3.1->3.4.0": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.3.1-3.4.0.patch"
            },`

Do I have to remove it or I add the new one like this ?

`"amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.4.0->3.4.3": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.3.1-3.4.3.patch"
            },`

Thank you for your help.

Kévin

**Comment by christianzichichi** [comment] 2020-04-21 09:49
Hi @KevinOxwork, 
you'll first have to remove them and restore the plugin version to the one originally bundled with your Magento installation (3.3.1). To do that, remove the lines from your composer.json, then from your Magento installation folder run the following:

`rm -rf vendor/amzn/amazon-pay-and-login-with-amazon-core-module/ vendor/amzn/amazon-pay-module/ vendor/amzn/login-with-amazon-module/`

then run the following to restore the plugin to its original state: 

`php bin/magento setup:update`

then you can proceed installing the new patch using this: https://gist.github.com/christianzichichi/79831e03451e17c491fb8cd7dc20b6f8

Thanks
Regards

Christian

**Comment by KevinOxwork** [comment] 2020-04-21 09:53
@christianzichichi,
Thank you for the quick reply, by doing this, I won't loose corrections from the older patch ?
Best regards,
Kévin

**Comment by christianzichichi** [comment] 2020-04-21 10:00
@KevinOxwork 

no you won't. 3.4.3 includes all the bugfixes of 3.4.0 and previous releases.

Regards
Christian

**Comment by KevinOxwork** [comment] 2020-04-28 06:06
Hi @christianzichichi !
I applied the patch but it did not solved my problem. I still not have Amazon Pay button on my add to cart popin and sometimes I have two buttons on my cart sidebar, sometines none. However I don't have js error anymore.
Do you have any ideas where problem could come from ? I think that because popin and cart sidebar are on the same page and the div id where amazon pay button is set have the same id, it cause conflicts. Problem is when I do not add product to my cart (so i don't show the popin) but already have products in my cart and want to show cart sidebar to preview it, I don't have any button this time.
Regards,
Kévin

**Comment by christianzichichi** [comment] 2020-04-28 14:29
Hi @KevinOxwork .
please contact us at payments-cp-devel@amazon.com with a full description of your issue, magento installation and plugin configuration. your issue seems different from the one described here. 

Thanks
Christian

**Comment by KevinOxwork** [comment] 2020-04-28 14:58
@christianzichichi , 
Thank you for the reply, I just send you an email.
Kévin

**Comment by aurel5542** [comment] 2021-05-25 11:19
Hello, this issue is still open. We can only update with composer to version": "3.4.1-p3". This is affecting the checkout (I think only in Mozilla browsers): The loader keeps spinning and not end loading so you can not enter your shipping adress. Sometimes it works. If you stay on the shipping adress site and keep refreshing the browser sometimes it works, sometimes endless loading. Mozilla shows this error: magento 2 Uncaught TypeError: G is null Button https://static-eu.payments-amazon.com/OffAmazonPayments/de/lpa/js/Widgets.js?nomin:2 _renderAmazonButton https:// - my shop url - /de_DE/Amazon_Payment/js/amazon-button.js:145 $.widget/</proxiedPrototype[prop]</< jQuery _create https:// - my shop url - /de_DE/Amazon_Payment/js/amazon-button.js:56 jQuery 3

we currently disabled Amazon pay completly. Is there a way of fixing this without deleting the whole plugin and reinstall?
Magento ver. 2.3.6-p1
Thank you

**Comment by christianzichichi** [comment] 2021-05-25 11:59
Hi @aurel5542 ,

in order to solve the issue you can either patch your current checkout integration: https://gist.github.com/christianzichichi/777bdfc834b357fb5ab72b3cf5d35d6d
or install our new extension from the marketplace: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html
https://amzn.github.io/amazon-payments-magento-2-plugin/

Thanks
Best

Christian

**Comment by aurel5542** [comment] 2021-05-25 12:24
> 
> 
> Hi @aurel5542 ,
> 
> in order to solve the issue you can either patch your current checkout integration: https://gist.github.com/christianzichichi/777bdfc834b357fb5ab72b3cf5d35d6d
> or install our new extension from the marketplace: https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html
> https://amzn.github.io/amazon-payments-magento-2-plugin/
> 
> Thanks
> Best
> 
> Christian

Hello Christian, thanks so much for your fast answer. I will check it asap. Best regards!
