### ISSUE TITLE
Amazon pay return error on checkout page

### ISSUE THREAD

**Issue by balwant20** [amzn/amazon-payments-magento-2-plugin#400] opened 2018-11-23 14:17 UTC
**What I expected**
Customer should placed order with amazon pay payment method

 **What happened instead**

on my Magento store sometimes customer facing the error on the checkout page when the customer wants to place the order with Amazon pay payment method.
It says "

**Important Message We're sorry, but there's a problem processing the order from this website. Please contact the seller for help with placing this order."**

 **Steps to reproduce the issue**

1) Added product into Cart

2) Login into Amazon

3) From Amazon checkout navigated to home page.

4) Again came back to Amazon checkout & found this error & at this time following errors were there in the console:

**"Uncaught Error: Unable to process binding "foreach: function()

{return $parent.elems() }
"" (Attaching screenshot for error)**

**My setup**

* Magento version: 2.2.4
* Amazon Pay Extension Version: 1.2.4
* PHP : 7.1.20
* Magento Edition: Community
* Shop URL : www.angara.com

![image-2018-06-29-16-57-32-211](https://user-images.githubusercontent.com/31465231/48947834-8dcd4280-ef58-11e8-9861-35a453fb9e5b.png)

**Comment by bjguillot** [comment] 2018-11-23 16:35
I have been unable to replicate the issue on your website when following your steps.  Does this happen for you every time, or intermittently?

I notice that my screen looks slightly different from your screen when going to this page.  For example, when I go to it, the box on the right titled "Shopping Cart" in your screenshot shows "Order Summary" on mine.  The red "Continue/Next: Review & Place Order" button in your screenshot shows "Review Order" on mine.  Your screenshot heading says "Secure Checkout", while mine does as well, but there is an icon of a padlock in front of the word "Secure".

Also, your screenshot mentions delivery dates "by Jun 29 - Jul 02", and the Windows timestamp on the bottom right of the screen shows 6/29/2018, so it looks to be a few months old.  Are you able to provide a more recent screenshot showing the issue?

It looks like you are using Chrome on Windows 10.  Can you confirm that?

**Comment by balwant20** [comment] 2018-11-23 17:05
@bjguillot thanks for your quick reply. actually we notice this issue few months back but then we thought there  is some network  issue. the above screenshot taken that time but   recently we can easily reproduce this isssue on our site. if you try 5-6 times in ipad then it reproducible or in desktop after try 9-10 times then it will reproduce. 
Did you ever faced the same issue on amazon pay? or you can give me any suggestions ,how can i prevents that error?

Thanks In advance...!!!

**Comment by tarishah** [comment] 2019-02-15 18:22
@balwant20  Is this still an issue?
If so, can you please reach out to use at payments-cp-devel@amazon.com referencing this GH issue and provide us Amazon Pay and Magento exception logs? 

This will help in further debugging the issue.

**Comment by christianzichichi** [comment] 2020-01-27 16:24
Hi @balwant20 ,

As we still cannot reproduce this I am going to have to go ahead and close this issue for now. If you are able to provide any screenshots or logs to payments-cp-devel@amazon.com, we would be glad to help you troubleshoot further - but at this point, we would also recommend upgrading your magento installation to the latest version.

Thanks
Regards

Christian

**Closed by christianzichichi** 2020-01-27 16:24 UTC
Labels: customer feedback required
