### ISSUE TITLE
Amazon Payment required field Issue

### ISSUE THREAD

**Issue by AgeValed** [amzn/amazon-payments-magento-2-plugin#217] opened 2018-04-27 19:18 UTC
Hi all, 
When I'm on the checkout page and login with amazon payment (test account created on Step 4 https://sellercentral.amazon.com/gp/homepage.html)

Then I select the shipping method and click on "Next" btn, nothing happens, but when I inspect the HTML I'm saw the from and I saw a lot of "This is a required field."
![amazonpay](https://user-images.githubusercontent.com/210677/39380557-60ebe6a4-4a35-11e8-9d69-c072908cc577.PNG)
#### Your setup

* Magento version: 2.2.2
* Amazon Pay Extension Version:  1.26
* Magento Edition: Community 
* JavaScript Console: 
![jsconsole](https://user-images.githubusercontent.com/210677/39380773-1b375340-4a36-11e8-9c58-8c177ffaf094.PNG)

I didn't found any solution for this particular issue
I hope somebody can help me with this, 

Regards,
-Pablo

#EDIT 

More Info, if I have an account already created works fine but if is a new user it's not working, in order to work I need to go to account page then add shipping information with all the required fields, save, and then amazon pay works.

**Comment by git312** [comment] 2018-05-02 10:00
Hello, 

got the same issue. Klick on continue button and nothing happens. Shipping Fields are required after klick.

If i use a registred customer account, it works fine, but without logging in nothing happens.

Regards,
Simon

**Comment by AgeValed** [comment] 2018-05-09 15:15
Any suggestion about this add to comment @islandskater43 & @danielneu people that accept previews Pull Request and @lemked Solutions Architect at Amazon

**Comment by AgeValed** [comment] 2018-05-09 16:10
@islandskater43 thanks, you have an ETA?

**Comment by git312** [comment] 2018-05-14 09:40
Hey @islandskater43 , 

sorry for the late response. Magento-Version is 2.2.3 and Amazon_Payments Module Version is 1.11.0.

**Comment by AgeValed** [comment] 2018-05-14 14:02
@islandskater43 any news from the support team?

**Comment by prayagr** [comment] 2018-05-30 06:03
Hi @AgeValed , our support team was unable to reproduce the issue. Here's what we tried:

Fresh 2.2.2 install.
Fresh 1.2.6 install.

Paths tried:
1. added item to cart
2. went to checkout and saw fields
3. used amazon pay button and logged in
4. Amazon wallet address block replaced fields.

1. Logged in as new user
2. Added item to cart
3. Went to checkout and saw Amazon wallet address block

1. Logged out and logged in again
2. Added item to cart
3. Went to checkout and saw Amazon wallet address block

It's possible that you are having issues because something else is breaking javascript on that page - another module, etc. Do you have a staging site where we can reproduce this issue? Please email us the details at payments-cp-devel@amazon.com

**Comment by prayagr** [comment] 2018-07-02 23:22
Hi @AgeValed , can you review my comment above?

**Comment by czettnersandor** [comment] 2018-11-13 20:58
Same issue here with Magento 2.2.2 and Amazon Pay 1.2.8

It's only happening in Chrome, it works fine on Firefox.

**Comment by prayagr** [comment] 2018-11-14 07:50
Hi @czettnersandor , do you use the ShipperHQ extension by any chance? We have seen this issue earlier on merchants using this extension.

If so, please let me know which version of ShipperHQ you are using.

**Comment by czettnersandor** [comment] 2018-11-14 16:10
@prayagr There's no shipperhq installed here. Further debugging it appears applepay is trying to fill the shipping address form field on login when the form is not yet in the DOM because of this condition:

```
            //check to see if user is logged out of amazon (otherwise shipping form won't be in DOM)
            if (!amazonStorage.isAmazonAccountLoggedIn) {
                populateShippingForm();
            }
```
It's not checking if the form is in the DOM, it's only checking the login status in `amazonStorage`

**Comment by prayagr** [comment] 2018-11-15 01:16
Thanks @czettnersandor for that info, is there an extension related to shipping or checkout that you are using?

I'll have our dev team look into this, but I don't believe this can be reproduced on a stock Magento setup. Any chance you can provide a staging URL for us to review? If you can, please share it with us at payments-cp-devel@amazon.com

**Comment by czettnersandor** [comment] 2018-11-16 16:52
@prayagr I already shared the url a few days ago

**Comment by prayagr** [comment] 2018-11-16 17:34
Hi @czettnersandor , thanks for sharing that information. We will review the issue on the store and get back to you.

**Comment by prayagr** [comment] 2018-12-11 21:52
Hi @czettnersandor , sorry for the late response, but we were unable to reproduce this issue on the staging site your provided. Did you fix the issue already or have you made any other changes around it?

**Comment by prayagr** [comment] 2018-12-17 17:36
Hi @czettnersandor , reaching out again to verify that you fixed the issue since we are unable to reproduce it. If that's the case, can you share what the issue was?

**Comment by tarishah** [comment] 2019-02-14 20:52
Closing this for now. Please reopen if this is still an issue.

**Closed by tarishah** 2019-02-14 20:52 UTC
