### ISSUE TITLE
no upgrade possible Magento 2.2.2. to 2.2.6 with latest amazon pay extension installed

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#360] opened 2018-10-10 08:18 UTC
Hi there,

there is an error after upgrading to magento 2.2.6 from 2.2.2 with the latest amazon pay extension installed.

When running setup:upgrade the command line shows this error which is related to your amazon extensio.

Could you pls act fast and offer a solution?

Thanks!

Module 'Magento_Sales':
Upgrading data.. PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Model\ResourceModel\Db\AbstractDb::load() must be an instance of Magento\Framework\Model\AbstractModel, string given, called in /srv/live/test/vendor/amzn/amazon-payments-magento-2-plugin/src/Login/Plugin/CustomerRepository.php on line 84 and defined in /srv/live/test/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:338
Stack trace:
#0 /srv/live/test/vendor/amzn/amazon-payments-magento-2-plugin/src/Login/Plugin/CustomerRepository.php(84): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load('6977', 'customer_id')
#1 /srv/live/test/vendor/amzn/amazon-payments-magento-2-plugin/src/Login/Plugin/CustomerRepository.php(59): Amazon\Login\Plugin\CustomerRepository->setAmazonIdExtensionAttribute(Object(Magento\Customer\Model\Data\Customer))
#2 /srv/live/test/vendor/magento/framework/Interception/Interceptor.php(146): Amazon\Login\Plugin\CustomerRepository->afterGetById(Object(Magento\Customer\Model\ResourceModel\Cus in /srv/live/test/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php on line 338
ch@vm1:~/

**Comment by andidhouse** [comment] 2018-10-10 11:06
After running:

composer remove amzn/amazon-payments-magento-2-plugin

the plugin is not removed but shows "deactivated" when running php bin/magento module:status

The problem is that a) the extension is not really removed from the system and b) the new amazon pay extension which comes with magento in 2.2.6 is not available in the backend.

Could you Gus pls offer a step by step fix for this problem as there are many people having this (there is also another report here).

Thanks,

André

**Comment by lemked** [comment] 2018-10-11 10:11
HI @andidhouse ,

We can confirm that there are issues with the upgrade process, that is caused by a change in the module name due to the core-bundling as well as a change in the php dependencies.

Can you list the content of your vendor/amzn/ directory of your M2 installation along with the installed PHP version?

Kind regards,
Daniel

**Comment by andidhouse** [comment] 2018-10-11 10:16
Hi Daniel,

php version: PHP version: 7.0.32-0ubuntu0.16.04.1
Module folder attached.

THanks,

André
![screen shot 2018-10-11 at 12 13 52](https://user-images.githubusercontent.com/16196483/46797454-80188080-cd4f-11e8-9b51-e533838025f2.png)

**Comment by andidhouse** [comment] 2018-10-13 07:37
Hi Daniel,

could you pls offer a solution here? We have a valid amazon contract we have to fulfill and at the moment amazon pay ist not available due to this major problem caused by your extension.

I also highly recommend stating this problem in your install docs as more and more people upgrade to 2.2.6 with your amazon extension installed - all will have the same problem.

How can we make 100% shure that the old amazon pay extension is completely removed and also the new one coming with magento 2.2.6 is untouched and valid.

thanks,

andré

**Comment by lemked** [comment] 2018-10-16 14:06
Hi @andidhouse ,

Sorry for the late response.

We have verified this on a clean Magento 2.2.2 installation and could not spot an issue when updating via the regular command-line based approach that is [documented on the Magento 2 docs](https://devdocs.magento.com/guides/v2.0/comp-mgr/cli/cli-upgrade.html).

After the update, Magento 2.2.6 should be running with version 2.1.0 of our extension. The obsolete directory `amazon-payments-magento-2-plugin` inside the `vendor/amzn` directory can then safely be removed with `composer remove amzn/amazon-payments-magento-2-plugin`.

As far as I understand, you are currently still encountering an error when running `composer upgrade`. If you have a staging environment available, can you please share back-end and SSH access credentials via payments-cp-devel@amazon.com so that we can investigate the issue?

Kind regards,
Daniel

**Comment by lemked** [comment] 2019-07-12 07:21
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2.

**Closed by lemked** 2019-07-12 07:21 UTC
Labels: ack, customer feedback required
