### ISSUE TITLE
Conflict with B2B module: Column 'entity_id' in where clause is ambiguous

### ISSUE THREAD

**Issue by bjguillot** [amzn/amazon-payments-magento-2-plugin#206] opened 2018-03-09 01:31 UTC
#### What is happening

When adding new record to history log quote is fetched from the DB using searchCriteria. The field it filters quote collection by is 'entity_id'. Negotiable quote entity doesn't have that field, but amazon_quote entity does. That is why it throws an error: "Column 'entity_id' in where clause is ambiguous ".

#### Your setup

* Magento version: 2.2 with B2B Module
* Amazon Pay Extension Version: 1.2.5
* Magento Edition: Enterprise (non-Cloud)

#### Error message from MySQL

SQLSTATE[23000]: Integrity constraint violation:
1052 Column 'entity_id' in where clause is ambiguous, query was: SELECT
`main_table`.*,
`extension_attribute_amazon_order_reference_id`.`amazon_order_reference_id`
AS `extension_attribute_amazon_order_reference_id_amazon_order_reference_id`,
`extension_attribute_negotiable_quote`.`quote_id` AS
`extension_attribute_negotiable_quote_quote_id`,
`extension_attribute_negotiable_quote`.`is_regular_quote` AS
`extension_attribute_negotiable_quote_is_regular_quote`,
`extension_attribute_negotiable_quote`.`status` AS
`extension_attribute_negotiable_quote_status`,
`extension_attribute_negotiable_quote`.`quote_name` AS
`extension_attribute_negotiable_quote_quote_name`,
`extension_attribute_negotiable_quote`.`expiration_period` AS
`extension_attribute_negotiable_quote_expiration_period`,
`extension_attribute_negotiable_quote`.`negotiated_price_type` AS
`extension_attribute_negotiable_quote_negotiated_price_type`,
`extension_attribute_negotiable_quote`.`negotiated_price_value` AS
`extension_attribute_negotiable_quote_negotiated_price_value`,
`extension_attribute_negotiable_quote`.`shipping_price` AS
`extension_attribute_negotiable_quote_shipping_price`,
`extension_attribute_negotiable_quote`.`has_unconfirmed_changes` AS
`extension_attribute_negotiable_quote_has_unconfirmed_changes`,
`extension_attribute_negotiable_quote`.`is_customer_price_changed` AS
`extension_attribute_negotiable_quote_is_customer_price_changed`,
`extension_attribute_negotiable_quote`.`is_shipping_tax_changed` AS
`extension_attribute_negotiable_quote_is_shipping_tax_changed`,
`extension_attribute_negotiable_quote`.`snapshot` AS
`extension_attribute_negotiable_quote_snapshot`,
`extension_attribute_negotiable_quote`.`applied_rule_ids` AS
`extension_attribute_negotiable_quote_applied_rule_ids`,
`extension_attribute_negotiable_quote`.`creator_id` AS
`extension_attribute_negotiable_quote_creator_id`,
`extension_attribute_negotiable_quote`.`creator_type` AS
`extension_attribute_negotiable_quote_creator_type`,
`extension_attribute_negotiable_quote`.`original_total_price` AS
`extension_attribute_negotiable_quote_original_total_price`,
`extension_attribute_negotiable_quote`.`base_original_total_price` AS
`extension_attribute_negotiable_quote_base_original_total_price`,
`extension_attribute_negotiable_quote`.`negotiated_total_price` AS
`extension_attribute_negotiable_quote_negotiated_total_price`,
`extension_attribute_negotiable_quote`.`base_negotiated_total_price` AS
`extension_attribute_negotiable_quote_base_negotiated_total_price` FROM
`quote` AS `main_table`
 LEFT JOIN `amazon_quote` AS `extension_attribute_amazon_order_reference_id`
ON main_table.entity_id =
extension_attribute_amazon_order_reference_id.quote_id
 LEFT JOIN `negotiable_quote` AS `extension_attribute_negotiable_quote` ON
main_table.entity_id = extension_attribute_negotiable_quote.quote_id WHERE
((`entity_id` = 1684565))

**Comment by Silarn** [comment] 2018-05-22 17:48
I believe the problem is that the extension attribute generator automatically adds (( entity_id = ###### )) to the query. However this conflicts with the amazon attribute because it has an entity_id column (which the negotiable_quote table does not).

**Comment by lemked** [comment] 2018-06-01 06:34
Tackled by https://github.com/amzn/amazon-payments-magento-2-plugin/pull/230 and https://github.com/amzn/amazon-payments-magento-2-plugin/pull/236.

Preparing release in https://github.com/amzn/amazon-payments-magento-2-plugin/tree/pre_1.2.7

**Comment by prayagr** [comment] 2018-06-20 05:17
Merged into master

**Closed by prayagr** 2018-06-20 05:17 UTC
