### ISSUE TITLE
OrderRepositoryInterface save bug on complete orders in CompleteOrder Observer

### ISSUE THREAD

**Issue by kilis** [amzn/amazon-payments-magento-2-plugin#51] opened 2017-04-03 12:03 UTC
#### What I expected

1. Create custom module that uses order repository interface and has completed orders in list
2. In a loop go all oreders and save with new data

#### What happened instead

Complete order interface on line 47 at $order->getStoredData() has 0 data
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/Observer/CompleteOrder.php

#### Steps to reproduce the issue
`$searchCriteria = $this->searchCriteriaBuilder->addFilter('customer_id', $masterUserId, 'eq')->create();`
`$orderList = $this->orderRepository->getList($searchCriteria);`

`foreach ($orderList as $order) {
                    $order->setCustomerId($selectedUserId);
                    $this->orderRepository->save($order);
                }`

#### Your setup

* Magento version: 2.1.4
* Magento Edition: Community
* Shop URL : %NaN%

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/Observer/CompleteOrder.php

**Comment by Silarn** [comment] 2017-04-20 07:19
Most likely this is because this observer is tied to the order save events rather than the place order events. I can elaborate more soon.

**Comment by OnTapSupport** [comment] 2017-04-25 08:30
We have written a module that includes the sample code that you provided, on a vanilla install of Magento, and we cannot replicate the issue you have faced. The code was successfully able to update the order object.

Did you try this on a vanilla version yourself, or was it on an existing site with other modules? If the latter, then it is probably some other influence affecting it.

**Comment by danielneu** [comment] 2017-04-27 09:38
Hi,

we will close this issue for now, as it is not reproducible by us.

Feel free to reach out again, if you think this is still an issue.

Best wishes 
Daniel

**Closed by danielneu** 2017-04-27 09:38 UTC
Labels: ack
