### ISSUE TITLE
Online invoice not Working

### ISSUE THREAD

**Issue by sanjusaju** [amzn/amazon-payments-magento-2-plugin#770] opened 2020-06-26 07:52 UTC
Hi,

I am trying to create an online invoice programmatically for orders which has payment method as Amazon pay. But I am getting error "Transaction has been declined. Please try again later". Creating invoice from admin is working fine. Please advise.

What I expected: Create invoice and capture payment

What happened instead: Getting error "Transaction has been declined. Please try again later". 

* Magento version: 2.3.5-p1
* Amazon Pay Extension Version:  3.4.1
* Magento Edition: Enterprise Cloud

Thanks!
Sanju

**Comment by christianzichichi** [comment] 2020-06-26 08:18
Hi @sanjusaju,
thanks for contacting us. Can you provide more details on how you are creating invoice programmatically (Amazon API calls used and parameters passed to them) ?

Thanks
Regards

Christian

**Comment by sanjusaju** [comment] 2020-06-26 08:22
Hi

I am creating invoice by passing parameter. I will send you sample invoice object, before calling invoice->register function.

[sample-invoice-objet.txt](https://github.com/amzn/amazon-payments-magento-2-plugin/files/4835842/sample-invoice-objet.txt)


Thanks!
sanju

**Comment by sanjusaju** [comment] 2020-06-26 09:44
Hello  christian,

Any Progress?

Thanks

**Comment by bear-ihor** [comment] 2020-06-26 20:08
Hi @sanjusaju,

[The invoice creation via REST API](https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-create-invoice.html) works perfectly for me. 
Did you create a custom PHP code for the invoice creation?
Could you, please, provide it?

Thank you.

**Comment by sanjusaju** [comment] 2020-06-28 03:13
Hi,

I am calling magento invoice creation code as part of my custom module. Can
you please share the invoice creation code via rest API I will check
whether it will works for me

**Comment by bear-ihor** [comment] 2020-06-29 15:11
@sanjusaju,

I just followed the Magento tutorial:
- **Endpoint**:
POST <host>/rest/<store_code>/V1/order/<order_id>/invoice
- **Headers**:
Content-Type: application/json
Authorization: Bearer <administrator token>
- **Payload**:
`{
  "capture": true,
  "notify": true
}`

**Comment by christianzichichi** [comment] 2020-06-30 08:25
Hi @sanjusaju ,

can you please let us know if you solved your issue?

Thanks
Regards

Christian

**Comment by sanjusaju** [comment] 2020-07-02 14:15
Hello christianzichichi and bear-ihor ,

It is working for me as well. Thanks for your support.

Thank you
Sanju

**Comment by sanjusaju** [comment] 2020-07-07 11:43
Hello bear-ihor ,

When I checked the order edit page on admin it does not show invoice item count, if I create invoice via magento rest API. But order  history and invoice tab has invoice details.
Please let me know if you faced the same issue and fixed it.

Thanks
![order-invoice](https://user-images.githubusercontent.com/67457168/86775670-328c8d00-c075-11ea-91ed-d09d2c76e1b3.PNG)

**Comment by bear-ihor** [comment] 2020-07-07 15:21
Hi @sanjusaju,

Partial capture is disabled in some regions, see [commit 3ad197a](https://github.com/amzn/amazon-payments-magento-2-plugin/commit/3ad197a2ab14d2f0fc93c3583d6da25b12a94271).

Thank you.

**Comment by christianzichichi** [comment] 2020-07-07 15:31
Hi @sanjusaju,
for EU/UK payment regions, partial captures have been disabled in the module due to PSD2 requirements (amount consistency). order total should be invoiced/captured and a partial refund issued (credit memo) if needed. Let us know if you have any other question

Thanks
Regards

Christian

**Comment by sanjusaju** [comment] 2020-07-08 08:45
Hello,

I am checking for US region. Not for EU/UK. Partial capture is working and online capture status is showing in order history section. But the order item grid does not have item invoice count. Any idea?

Thank you
Sanju

**Comment by bear-ihor** [comment] 2020-07-08 16:39
@sanjusaju,

AFAIK the Amazon Payment module has nothing to do with the invoiced qty.
It only receives from Magento the capturing amount for processing and isn't aware of how many qty's were invoiced.
I tried to reproduce the issue on Magento 2.3.5 with the payment module version 3.6.1 and the invoiced qty value was present:
<img width="1269" alt="Screen Shot 2020-07-08 at 9 16 29 AM" src="https://user-images.githubusercontent.com/61063191/86946143-d1110080-c0fe-11ea-8379-5627ef91a7b3.png">

Thank you.

**Comment by sanjusaju** [comment] 2020-07-09 13:17
Okay. Thank you for your information. If I create invoice manually from admin , then the invoice quantity is showing. Issue is only with invoice creation via Rest API

**Comment by bear-ihor** [comment] 2020-07-09 20:55
@sanjusaju,

An invoiced qty appeared for the ordered item when I created an invoice via REST API, see my screenshot above.
So either I'm doing something wrong, or you use there is another 3rd party extension, that influences the invoice qty visibility.

Thank you.

**Comment by sanjusaju** [comment] 2020-07-14 05:55
Hi,

I am trying to create an online invoice for an order which has 3 quantities and placed from Newyork, US. First I have created invoice for 2 quantities. The amount captured correctly. Then tried to create invoice fro remaining 1 quantity. But got the bellow error message.
"You have attempted to call an operation on an Order Reference object that is in a state where that operation is not allowed."


![partial_Capture](https://user-images.githubusercontent.com/67457168/87389565-960e4180-c5c4-11ea-8626-4fdecad19194.PNG)

Thanks!
Sanju

**Comment by bear-ihor** [comment] 2020-07-14 15:22
@sanjusaju,

As I remember you are using Amazon Pay Extension version 3.4.1, right?
The issue is fixed in the most recent version. 
Please, upgrade - https://gist.github.com/christianzichichi/7d0d76b541070c3cdea77554c391c571

Thank you.

**Comment by sanjusaju** [comment] 2020-07-16 06:52
Yes bear-ihor our version is 3.4.1
 "require": {
                "amzn/amazon-pay-and-login-with-amazon-core-module": "3.4.1",
                "amzn/amazon-pay-module": "3.4.1",
                "amzn/login-with-amazon-module": "3.4.1"
            },

**Comment by christianzichichi** [comment] 2020-07-16 07:58
hi @sanjusaju,
thanks for confirming. Using these instructions to update  https://gist.github.com/christianzichichi/7d0d76b541070c3cdea77554c391c571 will enable split shipments/multi-authorization and solve your issue

Thanks
Best
Christian

**Comment by sanjusaju** [comment] 2020-07-20 08:03
@christianzichichi ,

Can you please let me know what is the response code/approval code we received from amazon for a successull transaction.

Thanks!
Sanju

**Comment by christianzichichi** [comment] 2020-07-23 14:50
Hi @sanjusaju ,
if you are calling Amazon Pay API directly, you might want to take a look here:

https://developer.amazon.com/docs/eu/amazon-pay-api/authorization-states-and-reason-codes.html
https://developer.amazon.com/docs/eu/amazon-pay-api/capture-states-and-reason-codes.html

let me know if those answer your question.

Thanks
Regards

Christian

**Closed** 2020-07-27 15:25 UTC
Labels: ack, customer feedback required, ticket created

**Comment by sanjusaju** [comment] 2020-07-29 05:31
Hi,

Does your extension support admin ordres using amazon pay? We have placed admin order, but it does not show login popup , no amount authorized. Please provide details.

Thanks!
Sanju

**Comment by sanjusaju** [comment] 2020-07-29 05:34
Hi,

Also noticed one more issue wile testing with Amazon pay. For all amazon pay orders the billing address showing as 
Christopher C. Conn
4996 Rockford Mountain Lane
Appleton, Wisconsin, 54911
T: 000-000-0000

Why is it so? How it will behave for live account?

Thanks!
Sanju

**Comment by sanjusaju** [comment] 2020-07-29 13:34
FYI: Please note for admin orders the payment method showing as amazonlogin instead of amazon payment. Not sure why. May be this is causing the amount is not authorized.

select entity_id,method,last_trans_id,additional_information from sales_order_payment where parent_id in (975229,975247);
+-----------+----------------+-----------------------------+------------------------------------------------------------------------+
| entity_id | method         | last_trans_id               | additional_information                                                 |
+-----------+----------------+-----------------------------+------------------------------------------------------------------------+
|    974947 | amazonlogin    | NULL                        | {"method_title":"Amazon Pay"}                                          |
|    974965 | amazon_payment | S01-0945846-8331733-A028858 | {"sandbox_simulation_reference":"default","method_title":"Amazon Pay"} |
+-----------+----------------+-----------------------------+------------------------------------------------------------------------+

**Comment by sanjusaju** [comment] 2020-07-30 04:04
Hello @christianzichichi  Can you please check and respond to my last three comments. It is very urgent.

**Comment by christianzichichi** [comment] 2020-07-30 13:28
Hi @sanjusaju ,
I apologize for the delay here. 
- no, our extension does not support order creation from admin panel.
-  for US payment region, billing address is not returned by default by Amazon Pay. That billing address is a default one that Magento sets for sandbox orders. For Live orders, billing address will be copied over from shipping address, unless you collect it separately via standard Magento forms (applying custom code or using third party plugins)
- as said, we don't support orders created from admin panel so I'm not sure. amazonlogin comes from Login With Amazon feature (social login) 

If you have more questions or you need help, please contact us at payments-cp-devel@amazon.com , We'll be happy to assist you further.

Thanks, 
Best

Christian

**Comment by RayAnaya** [comment] 2020-07-30 19:09
@sanjusaju I just wanted to add to Christian's response:

> for US payment region, billing address is not returned by default by Amazon Pay. That billing address is a default one that Magento sets for sandbox orders. For Live orders, billing address will be copied over from shipping address, unless you collect it separately via standard Magento forms (applying custom code or using third party plugins)

The address is actually the default "test" billing address Amazon Pay provides for its Sandbox Buyer Accounts (the account you set up for testing purchases in Sandbox mode from Seller Central) so that information would definitely change once you move to Production.

Can you please share with us (payments-cp-devel@amazon.com) who you were working with to get your account enabled for the Billing Address feature?  As @christianzichichi  mentioned, this feature only works for the standard checkout flow with Magento right now, and I don't believe we ever intended for the admin-order use-case, but I'd like to learn more from you about how you intended to use it.
