### ISSUE TITLE
Magento 2.3.4 Existing customers can't checkout after upgrade

### ISSUE THREAD

**Issue by webamondo** [amzn/amazon-payments-magento-2-plugin#610] opened 2020-03-05 09:20 UTC
Just upgraded to 2.3.4 but existing customers can't move from step 1 in the checkout to step 2.

You need to be logged in as a customer that existed on 2.3.3.

Error 500 on /rest/STORE/V1/carts/mine/shipping-information

"Fatal Error: 'Uncaught Error: Call to a member function getAmazonOrderReferenceId() on null in \/srv\/public_html\/vendor\/amzn\/amazon-pay-module\/Plugin\/ShippingInformationManagement.php:85\nStack trace:\n#0 \/srv\/public_html\/ven$

#### What I expected

1. Customer should be able to select a previously used address and move to the payment method

#### What happened instead

1. Customer can't get passed the shipping methods
2. Error 500 on /rest/STORE/V1/carts/mine/shipping-information

#### Steps to reproduce the issue

1. Have Amazon pay enabled
2. Create customer in 2.3.3 with addresses
3. Upgrade to 2.3.4
4. Login as an existing customer
5. Go to checkout
6. Can't get passed Shipping method 

#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 3.3.1
* Magento Edition: Community
* JavaScript Console: 
![Screenshot 2020-03-05 at 09 18 40](https://user-images.githubusercontent.com/22942523/75966471-53c04f80-5ec2-11ea-98c4-c9294a5db283.png)

* Shop URL : www.notinthedoghouse.co.uk

**Comment by christianzichichi** [comment] 2020-03-05 15:19
Hi @webamondo , thanks for contacting us. Can you please send us the following details to payments-cp-devel@amazon.com ?

- staging URL (with Amazon Pay plugin in Sandbox Mode)
- credentials for a test account you used in 2.3.3 (if you have it available) that is now triggering that error in 2.3.4, we'll use it to reproduce the issue you are encountering and investigate. We'll also try to reproduce the issue ourselves as you described in a vanilla installation/upgrade 
- relevant staging/production logs of our extension showing the issue

Thanks

Christian

**Comment by webamondo** [comment] 2020-03-08 19:55
I'll see if I can get it to replicate on staging and send you the details

I've also found this in the php error log

[08-Mar-2020 19:52:49 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAmazonOrderReferenceId() on null in /srv/public_html/vendor/amzn/amazon-pay-module/Plugin/ShippingInformationManagement.php:85
Stack trace:
#0 /srv/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Amazon\Payment\Plugin\ShippingInformationManagement->beforeSaveAddressInformation(Object(Magento\Checkout\Model\ShippingInformationManagement\Interceptor),$
#1 /srv/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(43321, Object(Magento\Checkout\Model\ShippingInf$
#2 /srv/public_html/generated/code/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)
#3 [internal function]: Magento\Checkout\Model\ShippingInformationManage in /srv/public_html/vendor/amzn/amazon-pay-module/Plugin/ShippingInformationManagement.php on line 85

**Comment by nishpatel** [comment] 2020-03-09 07:52
For us this was due to the fact that when someone tries to log out using Amazon Pay there is a 500 error emitted via /amazon/logout/index

```
Uncaught exception 'TypeError' with message 'strpos() expects parameter 1 to be string, null given' in /data/webroot/*/*/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php:44
```
This result's into having the following error when you try to checkout using any payment method!

```
Uncaught exception 'Error' with message 'Call to a member function getAmazonOrderReferenceId() on null' in /data/webroot/*/*/vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Plugin/ShippingInformationManagement.php:85
```

We have come up with a fix for this. 

```
<type name="Magento\Framework\App\Response\Http">
        <plugin name="amazon_logout_bug_fix" type="Company\Module\Plugin\App\Response\Http" sortOrder="20"/>
</type>

public function afterGetContent(
     \Magento\Framework\App\Response\Http $subject,
     $content
) {
     return !$content ? "" : $content;
}
```

**Comment by webamondo** [comment] 2020-03-09 08:06
@nishpatel will you be creating a pull request so I can create a patch file?

**Comment by nishpatel** [comment] 2020-03-09 11:44
This didn't work for us in production mode so looking for a solution now as well. What we have found is that if you have logged out the session hasn't cleared properly hence no one can checkout using any other payment method. Please can you update us when you have a solution for this? We are using M2.3.4 thanks

**Comment by nishpatel** [comment] 2020-03-09 13:38
Ok we couldn't wait but share the trivial fix...

On line 85 you see this:

```
$amazonOrderReferenceId = $quote->getExtensionAttributes()
      ->getAmazonOrderReferenceId()
      ->getAmazonOrderReferenceId();
```

Before this please simply add the following:

```

if (!$quote->getExtensionAttributes()->getAmazonOrderReferenceId()
) {
     return $return;
}

This should fix the issue tested on our production for us.

**Comment by christianzichichi** [comment] 2020-03-10 17:11
Hi @webamondo and @nishpatel ,
we are trying to reproduce this issue on a vanilla installation with no luck. Could you please provide more details on how to reproduce it to payments-cp-devel@amazon.com (account used, staging view)? 
Meanwhile, the fix provided by @nishpatel has been validated and we confirm it's safe to use it. Thanks for your help with this.

Christian

**Comment by webamondo** [comment] 2020-03-13 15:52
@christianzichichi should we be waiting for releases via the magento2 core or are we safe bringing in newer versions via a composer require?

**Comment by christianzichichi** [comment] 2020-03-16 08:46
Hi @webamondo, 

we have not yet been able to reproduce this issue, so we are currently evaluating whether to include BearGroup@d491ad6 to the plugin (and the ship it into the next magento2 core versions). For the moment, I'd ask you to include that patch manually when you upgrade. 

Thanks
Christian

**Comment by live4soccer7** [comment] 2020-06-07 22:29
I can verify the fix provided by @nishpatel works well. We are developing a site and the amazon payment never worked (we started on 2.3.3) and we are now on 2.3.5-p1. I just implemented this on the most recent version and it is working well as far as I can tell.

**Comment by christianzichichi** [comment] 2020-06-08 18:16
Hi all,
The fix for this issue has been merged into the plugin codebase and will be delivered in the next Magento releases: https://github.com/amzn/amazon-payments-magento-2-plugin/commit/82f00e5125f594fc0e9d7f11057c6c873bd16913

Thank you all for your contribution

Regards
Christian

**Closed by christianzichichi** 2020-06-08 18:16 UTC
Labels: ticket created, waiting for release

**Comment by live4soccer7** [comment] 2020-06-08 18:46
That's very good to hear!

I'm just curious, has anyone done additional sandbox testing? If I login with an account and go all the way to the page where it says to place order and then back out of the checkout process (ie click on the homepage) it will send a transaction to Amazon Pay still for an authorization on what the order would have been IF it the order were placed, but it never actually was. The customer will then get an email and it shows up in the Amazon Pay section in your Amazon account and there is nothing on the Magento Backend.
