### ISSUE TITLE
Orders mostly always not showing in grid and can't update

### ISSUE THREAD

**Issue by live4soccer7** [amzn/amazon-payments-magento-2-plugin#1146] opened 2022-11-15 03:37 UTC
#### What I expected
Orders should show in grid. They are in magento because shipstation still picks them up. I can not find out why, but this does not always happen. Every once in a while an order will show up in the grid, however I can not update the order status. I click ship and upload shipping and the email will send, however it does not get updated on the grid and the tracking number is not visible under shipment. I can not create another shipment.

#### What happened instead

see above for full explanation

#### Steps to reproduce the issue

unknown at this time. The issues occurs 90% of the time.

#### Your setup

* Magento version: 2.4.4-p2
* Amazon Pay Extension Version: 5.14.1
* Magento Edition: Community

**Comment by sgabhart22** [comment] 2022-11-15 17:06
Hello @live4soccer7 ,

Would you happen to have a staging site where this is reproducible, or have you only noticed this in a live environment? It's odd that the orders seem to be getting placed without problem, but display in the order grid and status manipulation is impossible.

If a test environment isn't available where we can see the issue, would you be able to provide an excerpt of the paywithamazon.log file from around the time you've been having problems with AP orders? There might be some information there that could help. Otherwise, there may be some integration conflicts with Shipstation or another third-party extension.

Thanks,
Spencer

**Comment by live4soccer7** [comment] 2022-11-15 17:10
@sgabhart22 

I believe I've had logging disabled, but I can go ahead and enable it and post back. I do not have a staging environment for this. I've always found staging can be difficult with payment gateways. Hopefully, I will have something for you by the end of the day.

**Comment by sgabhart22** [comment] 2022-11-29 19:21
Hi again @live4soccer7 , just curious if this problem has persisted or if you've been able to capture anything in the logs. Let us know!

Spencer

**Comment by sgabhart22** [comment] 2022-12-19 16:25
Hey @live4soccer7 ,

Since we haven't had any updates in a while, we'll go ahead and close this issue. If the problem still exists and you have been able to find any logs/repro steps/new information about the issue, please feel free to reopen!

Thanks,
Spencer

**Comment by NisiPasa** [comment] 2022-12-19 16:41
Closing. Please reopen if the issue still occurs.

**Closed by NisiPasa** 2022-12-19 16:41 UTC
