### ISSUE TITLE
Cannot create invoice for Order Magento 2.4.5

### ISSUE THREAD

**Issue by bmitchell-ldg** [amzn/amazon-payments-magento-2-plugin#1199] opened 2023-07-04 09:12 UTC
#### What I expected
No errors when placing orders 

#### What happened instead

The order is invoiced, moves to processing and is captured as expected but the following error is thrown "Cannot create invoice for Order" 
![Screenshot 2023-07-04 at 10 09 07](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/32c252a3-758a-4f8e-a221-168fba206d12)

#### Steps to reproduce the issue

Place an order with the below config set and the error is thrown for every order
#### Your setup

* Magento version: 2.4.5
* Amazon Pay Extension Version: 5.15.0
* Magento Edition: Enterprise 
* Sandbox : Enabled
* Amazon - Sign In : Enabled
* Payment : Change when order is placed
* Authorisation Mode: Automatic 
* Shop URL : 

Findings so far:
in Charge.php the loadInvoice function doesn't return any invoices. 
![Screenshot 2023-07-04 at 10 03 31](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/2745c640-840b-41de-ba0b-658ebf4924f5)
![Screenshot 2023-07-04 at 10 07 31](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/b3f179b6-928d-4c7a-a251-49685e379f66)

The invoice exists in M2, but it doesn't have the TRANSACTION_ID associated to it at this point. 

CheckoutSessionManagement.php line 768 is where the capture is made
![1](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/4c174f4f-7a5b-4789-8e27-3d1429019671)
![2](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/efc0c529-6dd6-43e8-9378-0d10091fd452)

In that capture loadInvoice is used and loadInvoice is the function filtering on TRANSACTION_ID
![3](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/ea181c1b-d353-42e2-a5e5-087e41d8c99a)

But if you go back to CheckoutSessionManagement.php the TRANSACTION_ID isn’t populated with the $chargeId until further down line 810
![4](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/3041320/ea5132c4-d425-456f-b9d9-b4f59bf4a1a0)
Seems like the transaction_id is being populated too late.

To make sure it wasn't a conflict caused by a custom module or 3rd party module we also disabled everything back to core Magento using the Luma theme and the error was still thrown.

**Comment by lcouget** [comment] 2023-07-11 11:27
Hi @bmitchell-ldg 

Thank you for reporting this issue.

We noticed that even "cannot create invoice" error message is displayed, the invoice is successfully created. Here is an example:

![image-20230704-210619](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/8595500/3d3b6cb8-81a6-4869-84fd-01274a95e091)

![image-20230704-210833](https://github.com/amzn/amazon-payments-magento-2-plugin/assets/8595500/a6304b4f-e267-4594-862b-81e99ef66ca8)

We will continue investigating the issue to avoid the appearance of this error message during payment capture process. 

Thank you. Regards,

**Comment by dallin-beargroup** [comment] 2023-07-19 19:22
Was able to replicate as well.
The steps to reproduce are accurate, and the issue definitely centers around Payment : Charge when order is placed.
As noted, the order appears to be in good health with exception to the extra order comment from \Amazon\Pay\Model\AsyncManagement\Charge::capture
The second order comment (not throwing err) comes from \Amazon\Pay\Model\CheckoutSessionManagement::addCaptureComment 
This needs further review.

**Comment by sgabhart22** [comment] 2023-07-25 15:40
Hello @bmitchell-ldg ,

Thanks again for the call out here, definitely an annoying bit of noise on order history comments if nothing else. I've done some testing with Auth & Capture ('Charge when the order is placed') and both Authorization Modes, and I believe a reasonable solution is to also check the auth mode before calling the asyncCharge function. It seems like everything behaves as expected if the auth mode is Immediate, but we only see this errant comment in Automatic mode.

The attached patch should address this reasonably, since in Automatic mode, the capture will be initiated asynchronously later if it can't be done right away anyway. Please let us know if you're able to try it out or have any different solutions!

[gh1199.patch.txt](https://github.com/amzn/amazon-payments-magento-2-plugin/files/12163065/gh1199.patch.txt)

Thanks again,
Spencer

**Comment by bmitchell-ldg** [comment] 2023-07-26 12:01
Thank you Spencer, i will apply that patch now and let you know if it resolves the issues.
Thanks,
Bev

**Comment by bmitchell-ldg** [comment] 2023-07-27 11:26
Hello @sgabhart22 ,
The patch has been applied and resolved the issue.
Thanks,
Bev

**Comment by sgabhart22** [comment] 2023-07-27 12:52
Great news @bmitchell-ldg ! I appreciate the patience and feedback here, we'll go ahead and close this issue for now but keep our internal ticket open for tracking. This fix (or something very similar) will likely be included in an upcoming release.

Thanks again,
Spencer

**Closed** 2023-07-27 13:19 UTC
