### ISSUE TITLE
errors AmountNotSet and PaymentPlanNotSet on checkout when customer logged in

### ISSUE THREAD

**Issue by szubariev** [amzn/amazon-payments-magento-2-plugin#116] opened 2017-08-28 10:25 UTC
#### What I expected
To see shipping methods on checkout

Logged in customer should be able to do proceed amazon checkout.

#### What happened instead
When using amazon checkout  - always loading wheel seen on "Shipping Methods" section on one page checkout

Always see loading wheel on "Shipping Methods" section of one page checkout

#### Steps to reproduce the issue
1) log in to magento store
2) place product to cart
3) proceed to checkout (in any way)
4) press "amazon checkout button"
5) login to amazon account in pop up window
6) select shipping address
7) forever loading wheel on "Shipping Address" section

#### Your setup

* Magento version: 2.1.8
* Magento Edition: Community

#### checkout page screenshot
![screenshot from 2017-08-28 13-12-19](https://user-images.githubusercontent.com/5457461/29769871-dc00c6d4-8bf4-11e7-92b0-5dacf6adaeba.png)

**Comment by szubariev** [comment] 2017-08-28 17:22
with a bit of digging i see the next:

1) loading wheel is set with [`amazonStorage.isShippingMethodsLoading(true);` in `Amazon_Payment/js/view/checkout-widget-address.js` on line 94](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/eb6135ae7fa1fb2428581b32bfc30e75387c026e/src/Payment/view/frontend/web/js/view/checkout-widget-address.js#L94) and `getShippingAddressFromAmazon` method  called each time amazon address changed in widget
2) loading wheel goes off on address error
3) when address successfully loaded - wheel don't go to off state specifically inside widget code, just [`checkoutDataResolver.resolveShippingAddress();` called in `Amazon_Payment/js/view/checkout-widget-address.js` on line 118](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/eb6135ae7fa1fb2428581b32bfc30e75387c026e/src/Payment/view/frontend/web/js/view/checkout-widget-address.js#L118)
4) because of `shippingAddress` variable is already set from logged in customer object on page load before amazon scripts - there is no further action inside [`Magento_Checkout/js/model/checkout-data-resolver.js` on line 99](https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Checkout/view/frontend/web/js/model/checkout-data-resolver.js#L99)

So it seems like address endpoint in shipping-rate-processor's method getRates should be called each time amazon address changed, or maybe do `amazonStorage.isShippingMethodsLoading(false);` after `checkoutDataResolver.resolveShippingAddress();` in `Amazon_Payment/js/view/checkout-widget-address.js`

**Comment by aholovan** [comment] 2017-08-29 09:30
Hi @szubariev, 

Please, take a look on https://github.com/amzn/amazon-payments-magento-2-plugin/issues/88
Seems it would help.

**Comment by danielneu** [comment] 2017-08-29 09:41
Closing this as a duplicate of #88, thanks @aholovan

**Closed by danielneu** 2017-08-29 09:41 UTC
Labels: bug, duplicate
