### ISSUE TITLE
Unable to uninstall old version of Amazon Payments

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-2-plugin#325] opened 2018-08-21 18:24 UTC
I saw today that you guys updated your extension and changed support for other Magento 2 versions. We are currently using Magento 2.2.5 and Amazon Pay 1.2.6. I went to upgrade to Amazon Pay 2.x as per your home page on github but after running the update I realized the extension version wasn't changing in the database. After a little bit of investigation I realized that somehow 2 version of Amazon Pay were installed and I can only remove the newest version as that's what is registered in my composer file. Please see attached photos. I would like to remove the old installation folder and keep the new one so we can continue getting updates via composer. Do you guys have a fix for this? If I manually remove the folder I get an error when I run php bin/magento setup:di:compile

![amazon_installation](https://user-images.githubusercontent.com/12579419/44421134-bc98de80-a54d-11e8-9670-06ad55a0fac6.JPG)

* Magento version: 2.2.5
* Amazon Pay Extension Version: Unknown + Newest Version
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : https://dev.precisiontools.com

Thanks

**Comment by tarishah** [comment] 2018-08-24 20:49
@jfain189 Have you followed our [documentation](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#un-install-method) for uninstalling the Amazon Pay extension?

Look forward to hear from you
Tarini

**Comment by jfain189** [comment] 2018-08-24 20:58
Hi Tarini,

Thank you for the prompt reply. I tried executing the uninstall command via composer command but it says there's no package to uninstall. Please see the pictures below. Amazon payments is still installed on the website.

![amazon2](https://user-images.githubusercontent.com/12579419/44607564-d9881880-a7be-11e8-85cd-15826107629a.JPG)

![disabled](https://user-images.githubusercontent.com/12579419/44607566-dbea7280-a7be-11e8-96b2-2724a71e9445.JPG)

**Comment by kornblumenapotheke** [comment] 2018-08-25 09:32
Same problem here!

I tried to uninstall manually, now i get

Warning: require(/var/www/vhosts/meineapo.at/httpdocs/vendor/composer/../amzn/login-with-amazon-module/registration.php): failed to open stream: No such file or directory in /var/www/vhosts/meineapo.at/httpdocs/vendor/composer/autoload_real.php on line 70

anyone able to help?

**Comment by lemked** [comment] 2018-09-05 06:09
Hi @kornblumenapotheke 

We can confirm this issue and are currently looking into it.

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-09-27 10:29
Hi @jfain189 ,

Is it possible for you to update to Magento 2.2.6? This includes (core-bundled extension) the latest version of our extension (2.1.0) and should replace the current extension installed on your system. You should be able to remove the reference to the amazon-payments-magento-2-plugin package (the one via provide here via GitHub, so "non-bundled") via 'composer remove amzn/amazon-payments-magento-2-plugin'. Let me know if that works for you.

@kornblumenapotheke , can you mention the Magento version you are using?

Kind regards,
Daniel

**Comment by jfain189** [comment] 2018-09-28 14:51
Hi Daniel,

The other extension versions are still present. Here's what I did:
Updated composer.json to include Mage 2.2.6 (we were using 2.2.5)
composer update
composer remove amzn/amazon-payments-magento-2-plugin
php bin/magento setup:upgrade
php bin/magento setup:di:compile
composer require amzn/amazon-payments-magento-2-plugin
php bin/magento module:enable Amazon_Core Amazon_Login Amazon_Payment
php bin/magento setup:upgrade
php bin/magento setup:di:compile

I attached a photo of my amazon directory. Now there's 5 different extensions here but the "amazon-payments-magento-2-plugin" seems to be the active one
![amazon_dir](https://user-images.githubusercontent.com/12579419/46215880-72eda180-c30c-11e8-895c-4ec2fa1e6322.JPG)


During the composer update I did get this warning:
amzn/amazon-pay-module suggests installing magento/module-scalable-checkout (100.2.*)
amzn/amazon-pay-module suggests installing magento/module-scalable-oms (100.2.*)

I looked it up and scalable checkout is a Magento Enterprise module. We are using community edition.

**Comment by andidhouse** [comment] 2018-10-10 11:03
Hi there,

we have exact the same problem. We upgraded magento from 2.2.2 to magento 2.2.6 - with the latest amazon extension installed.

After we upgraded we did run php bin/magento setup:upgrade to upgrade the database - then an amazon error appears and the upgrade can not be finished. 

The only way was to run:
composer remove amzn/amazon-payments-magento-2-plugin

Then the upgrade got working.

BUT:
The problem is that now the "old" amazon extension is still under "deactivated" modules - AND there is no new version of the amazon extension available in the backend.

Could you guys pls offer a solution for this asap as this is reproducible like you can see here.

THanks!

André

**Comment by leandrosunrise** [comment] 2018-10-17 19:02
Hi, 
We had the same exact issue. We upgraded from magento 2.2.5 to 2.2.6 and  after running  setup:upgrade we encounter the following  problem: "Please update your modules: Run \"composer install\" from the Magento root directory.\nThe following modules are outdated: Amazon_Core db data version: defined in codebase - 2.1.0, currently installed - 2.2.1. 

To fix the problem I when into the database and in the "setup_module" table I removed Amazon_Core, Amazon_Login, Amazon_Payment  and then I run php bin/magento setup:upgrade
php bin/magento setup:di:compile.

Hope this solution helps somebody.
thanks.

**Comment by andidhouse** [comment] 2018-10-18 06:53
Hi @leandrosunrise,

thanks for sharing.

If you delete the amazon entries in the "setup_module" table - is the amazon extension which comes natively with magento 2.2.6 working or also deleted?

In our table (we upgraded from 2.2.2 to 2.2.6) the table shows some wrong information (see screen).

Thanks,

André

![screen shot 2018-10-17 at 22 02 24](https://user-images.githubusercontent.com/16196483/47136171-3b429b80-d2b3-11e8-82b8-e7098051d4e1.png)

**Comment by leandrosunrise** [comment] 2018-10-18 14:43
Hi @andidhouse , This are the steps I took. Always remember to make changes on dev before moving into production.
 

1. composer require magento/product-community-edition 2.2.6 --no-update
2. composer update
3. remove folder vendor/amzn
4. composer install && composer update - make sure compser can write into the vendor folder.
5. setup:upgrade && setup:di:compile && setup:static-content-deploy
6. in db in the "setup_module" table remove Amazon_Core, Amazon_Login, Amazon_Payment.
7. run setup:upgrade && setup:di:compile && setup:static-content-deploy again. 
8. sometimes it might be necessary to also remove Klarna_Core, Klarna_Kp, Klarna_Ordermanagement
9.  and the Vertex_Tax from the "setup_module" table as well.

I also would suggest to do the upgrades incrementally. that is upgrade 2.2.3 then 2.2.4, etc. 

Hope it helps.

**Comment by RayAnaya** [comment] 2020-01-25 03:03
Hello all, As it's been a year since this issue was last reported, I am hoping that everyone has managed to upgrade and uninstall / remove older versions of the Amazon Pay plugin.

We have had several major new versions since this issue, and so I'm going to go ahead and close this issue for now - but welcome you to re-open if you still experience problems with more recent versions.

**Closed by RayAnaya** 2020-01-25 03:03 UTC
Labels: ack, customer feedback required
