### ISSUE TITLE
Duplicated orders with the same Transaction ID

### ISSUE THREAD

**Issue by Leone** [amzn/amazon-payments-magento-2-plugin#164] opened 2017-12-07 12:05 UTC
Hi,

the configuration:

* Magento version: 2.1.7
* Magento Edition: Community
* PHP version: 7.0
* Amazon Pay: 1.2.0

Payment Configuration:
- Payment Action - Charge on Order
- Authorization Mode - Synchronous
- Update Mechanism - Data Polling via Cron Job

**Issue**:
We found several duplicated orders in the admin panel, all with Amazon Payment method.
The data in duplicated orders is the same, only orderId and incrementID are different. Transaction ID is also the same.

Comment History in the first order:

> Nov 15, 2017 11:35:03 AM Payment Review
> Nov 15, 2017 11:35:03 AM Invoice #00000xxxx created
> Nov 15, 2017 11:45:02 AM Processing
> Nov 21, 2017 8:42:40 AM Shipment #00000xxxx created

Comment History in the second order:

> Nov 24, 2017 8:14:59 PM Processing
> Nov 24, 2017 8:14:59 PM Invoice #00000xxxx created
> Nov 24, 2017 8:15:00 PM Complete
> Nov 24, 2017 8:15:00 PM Shipment #00000xxxx created

**Comment by danielneu** [comment] 2017-12-07 13:51
Hi,

I would like to have our experts have a look at this.
Is it possible to share contact and access details to a staging system via mail: payments-cp-devel@amazon.com

I will then connect you with the right people.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-12-20 10:39
Hi @Leone 

could you share the details I asked for above with us?
We would be happy to find the cause for this with and for you.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-12-22 11:06
Closing, due to lacking feedback.

**Closed by danielneu** 2017-12-22 11:06 UTC
Labels: customer feedback required, needs investigation
