### ISSUE TITLE
Login redirect issue on mobile

### ISSUE THREAD

**Issue by aholovan** [amzn/amazon-payments-magento-2-plugin#111] opened 2017-08-23 09:27 UTC
#### What I expected

Customer should be redirected to checkout after the login via https://www.amazon.com/ap/signin?.. page.

#### What happened instead

When customer logged in via mobile he is not redirected to checkout page. Page is freezed with "You will be redirected shortly..." message.

#### Steps to reproduce the issue

1 - Login with Amazon, add default address in my account, add an item and do purchase
2 - Then logout.
3 - Start again as a guest from mobile and add item to cart
4 - Login with Amazon again from mobile. During this You will be redirected to https://www.amazon.com signin form.
5 - Enter relevant credentials. You will be redirected to the site back to page https://site.com/amazon/login/processAuthHash/#access_token=....
6) You will see the message "You will be redirected shortly..." and the page will freezed. 

#### Your setup

Magento version: 2.1.7. with all built caches enabled.
Magento Edition: Enterprise
JavaScript Console: There are no errors in console.

**Comment by aholovan** [comment] 2017-08-23 09:34
Seems AmazonRedirect widget initializated likely in wrong way. 
In details - Amazon_Login/js/amazon-redirect.js file has the code which has "subscription" on amazonCore.amazonDefined observable function in core js:

> amazonCore.amazonDefined.subscribe(function () {
                //only set this on the redirect page
                amazon.Login.setUseCookie(true);
                amazonCore.verifyAmazonLoggedIn().then(function (loggedIn) {
                    if (loggedIn) {
                        self.redirect();
                    }
                }, 0);
            }, this);

During debug I saw that this code does not work because amazonDefined(true) is set in core js file before initialization of the render widget.

So, I've added some fixes in oAuthRedirect.phtml template to init widget in another way by require function.

@danielneu,  please, check the issue and the fix https://github.com/amzn/amazon-payments-magento-2-plugin/pull/112

Thanks.

**Comment by danielneu** [comment] 2017-08-23 09:50
handed over for review. Thanks a lot for filing this and providing a possible fix at the same time.

Best wishes 
Daniel

**Comment by clickdigitalinteractive** [comment] 2017-08-23 10:22
noticed this also sometimes, I will check the logs when it does happen, I thought it was related to our other issue or slow connection.

**Comment by clickdigitalinteractive** [comment] 2017-08-31 07:31
This fix worked flawless for us.

**Comment by danielneu** [comment] 2017-08-31 09:44
Thanks for reporting back. We are hoping to have this verified soon and get it in.

**Comment by danielneu** [comment] 2017-08-31 09:49
This was merged into master and will be part of the next release.

Thanks for the contribution.

**Closed by danielneu** 2017-08-31 09:49 UTC
Labels: ack, bug

**Comment by EmilyPepperman** [comment] 2017-09-15 02:28
I would like this issue reopened... having a very similar issue... 
We are on: Magento 2.1.8 with 1.1.4 Amazon Pay extension

On mobile... the only difference is I didn't get the "redirected" message, 

How we recreated: 

View shopping cart
Select Amazon Pay
Login popup appears
Successfully Login with amazon credentials (including my 2fa)
returns to cart (that's the error in behavior expected... should continue with checkout)
Selecting Amazon Pay again just results in same loop

We have turned off Amazon Pay for now till resolved. Seems to be issue on mobile mainly... I could do more testing but didn't want to leave enabled on our production site.

**Comment by danielneu** [comment] 2017-09-15 08:18
Hi @EmilyPepperman ,

this seems to be a different issue. I also tried to reproduce it, but it was always working as expected for me.

Can you share more information?

* Device
* OS version
* Browser used
* Returning customer or new customer?
* logs available?
* staging site where it is reproducible?

I tried to reproduce as a fresh customer, as a returning Amazon Pay customer and as a returning customer that manually registered.

Anything in this area which is not working is serious, I will therefor create a ticket with our experts to have this double checked and I will also inform Matt about this request, I believe you have been in touch earlier, right? Maybe he can support you during day time to get you back live soon.

Best wishes 
Daniel

**Comment by n2diving-dgx** [comment] 2017-09-15 13:47
Mark for Emily here... since I was the one to first see it...
The environment was a Samsung S8+, Android 7.0, Chrome 60.0.3112.116, Returning customer, no logs but I can show you screen shots.   We don't have a stating site configured to reproduce but can create if need be... Emily or I could re-enable Amazon Pay on the live site  for a time if you need to test.

**Comment by pronto2000** [comment] 2017-09-20 16:32
I looked into this issue and I agree with @danielneu -- it's a different one. Just this issue blocked it most of times.

Unfortunately I was unable to reproduce the issue, so it might require certain conditions to be met. Creating a staging environment for testing the problem is probably the best way to approach it -- to get to the bottom of it may require more than couple of minutes.

Also once there's a test environment I would really appreaciate it if you create an exact step-by-step list of actions from opening page first time to the issue to manifest. This might look like unnecessary overkill, but it helps to guarantee that all conditions are met and thus save time further down the road.

PS. Once more thing. I think I managed to achieve similar (maybe the same) condition once. I logged in using Amazon Login from Sign In page, then I put a product to the cart and clicked Amazon Pay (product page). I was redirected to the Sign In page. Also I wasn't  logged in when this happens. All further attempts to log in / pay with Amazon failed (either the page was reloaded or I was redirected to Sign in page). The problem disappeared when I emptied browser cache and I was unable to reproduce it again.

**Comment by danielneu** [comment] 2017-09-21 09:31
@n2diving-dgx @EmilyPepperman 

Are you able to share this information? Would you also be willing to create a new issue to keep track of this?
Sharing instance details and anything you don't want to see here can be done via mail.
Share it either with Matt directly or with payments-cp-devel@amazon.com.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-09-26 08:17
Hi @n2diving-dgx @EmilyPepperman 

we would love to help you, but are still not able to reproduce in our systems.
Are you able and willing to share access to a staging site and create a new issue with us to handle this?

For more details see my last comment.

Thanks
Daniel

**Comment by EmilyPepperman** [comment] 2017-09-26 14:55
Hi @danielneu We just updated our site to 2.1.9 this morning.. we will see if we have any issue. I think after rerunning a static content deploy we were not able to reproduce again. Thank you for reaching out!
