### ISSUE TITLE
Unable to checkout with Amazon Pay with error "No such entity with orderId = 289207"

### ISSUE THREAD

**Issue by shilpsauce** [amzn/amazon-payments-magento-2-plugin#408] opened 2019-01-03 18:22 UTC
#### What I expected
Successful checkout

#### What happened instead

I got an error saying that the orderId does not exist. The exact message is: "No such entity with orderId = 289207"

#### Steps to reproduce the issue

1. After amazon pay has been setup, checkout with Amazon Pay as a guest user.
2. Sign in to the magento store.
3. Checkout again with Amazon Pay. (Amazon Pay login will not be required during this second checkout since the user is already logged in)
4. The order will be authorized in Amazon, but this error will show in the frontend, and the order will not be visible on the magento admin orders screen.

#### Your setup

* Magento version: 2.2.7
* Amazon Pay Extension Version: 2.1.2
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : test environement
![screen shot 2019-01-03 at 12 09 13 pm](https://user-images.githubusercontent.com/5776197/50654034-1f18d700-0f51-11e9-9861-15b7f5fb322a.png)

![screen shot 2019-01-03 at 12 15 19 pm](https://user-images.githubusercontent.com/5776197/50654076-45d70d80-0f51-11e9-8648-3dc69d1be700.png)

response from request /rest/default/V2/carts/mine/payment-information

{
  "message": "No such entity with orderId = 289207",
  "trace": "#0 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(800730, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#1 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(800730, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#3 \/Sites\/magestead\/Code\/banyanbotanicals.com\/generated\/code\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#4 [internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(800730, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#5 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#6 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/module-webapi\/Controller\/Rest.php(244): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#7 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#9 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/Sites\/magestead\/Code\/banyanbotanicals.com\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#11 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/Sites\/magestead\/Code\/banyanbotanicals.com\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#13 \/Sites\/magestead\/Code\/banyanbotanicals.com\/vendor\/magento\/framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#14 \/Sites\/magestead\/Code\/banyanbotanicals.com\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#15 {main}"
}

The exception is thrown in the following: `Magento\Sales\Model\ResourceModel\Order\Plugin\Authorization` on line 45.

`$order->getCustomerId()` returns "0" and `$this->userContext->getUserId()` returns the logged in user's userId.

**Comment by prayagr** [comment] 2019-01-03 21:01
Thanks for reporting the issue @shilpsauce. It's strange you are seeing this and I was not able to reproduce this for an M2.3.0 instance - I will try this out again after setting up a M2.2.7 instance and let you know it goes.

**Comment by shilpsauce** [comment] 2019-01-04 20:42
Thanks for checking, I just tried again, and was able to recreate the issue. For the 2 consecutive checkouts, I used the checkout page. I'm not sure if it makes a difference though. I think it has something to do with the Amazon Login session staying the same even though the magento session changes after logging in.

I noticed that if I checkout while being signed in first, and then checkout after signing out, I need to enter my Amazon credentials during both checkouts. If I checkout as guest first, and then as a signed in user, I only have to put in my Amazon credentials the first time.

**Comment by lemked** [comment] 2019-01-07 08:10
Hi @shilpsauce ,

I've tried reproducing this on a M2.2.7 installation with Amazon Pay 2.1.2, without success. Can you please outline the exact steps you have taken to reproduce the problem (along with screenshots)?

This is what I have tried:

- disable "Login with Amazon" in the extension configuration
- go to product page, add item to the cart
- go to cart page, click Amazon Pay button
- log in with Amazon account
- confirm shipping
- confirm payment

On the confirmation page, do NOT create an account. Then:
- go to product page, add item to the cart
- go to cart page, click Amazon Pay button (log in not required anymore now)
- confirm shipping
- confirm payment

On the confirmation page, now DO create an account. Will be automatically logged in. Then:
- go to product page, add item to the cart
- go to cart page, click Amazon Pay button (log in not required anymore now)
- confirm shipping
- confirm payment

For those three purchases, I couldn't reproduce any error. Please let me know if you have performed any steps other than those.

Kind regards,
Daniel

**Comment by shilpsauce** [comment] 2019-01-07 15:46
@lemked, Thanks for looking into this issue. Your steps are a little different from mine, and I can see how you were not able to reproduce the issue. Here are the exact steps.

Pre-requisites:
1. Amazon Pay module installed and enabled with the Login with Amazon Pay setting disabled.
2. A customer account created in Magento directly with username and password.
3. Browser: Google Chrome 

Steps:
1. Open Google Chrome in Incognito Mode
2. Navigate to any product page
3. Add product to cart (will get add to cart successful message and cart will be updated)
4. From the mini cart, click "Go To Cart" (user is taken to cart page)
5. From the cart page, click "Amazon Pay" (amazon pay sign in window opens)
6. Fill in the Amazon Pay user info and click "Sign in Using Secure Server" (Amazon Window closes and user is taken to the checkout page)
7. Keep all the default settings for email, shipping address, and shipping option and click "Continue to Payment and Review" (user is take to payment page)
8. Keeping all the defaults on the payment page, click "Place Order" (User is navigated to Order Confirmation Page)
9. Click "Sign In" at the top right of the page (user is taken to login page)
10. Sign in with Magento user credentials (user is logged in)
11. Navigate to product page and add item to cart (Item is successfully added to cart)
12. From the mini cart, click "Go To Cart" (User is taken to cart page)
13. Select Amazon Pay for checkout from the cart page (User is taken directly to the checkout page because the user had signed in during the previous checkout. There is no Amazon Sign In Window.)
14. Keeping the default selections for address and select any shipping method if not preselected, click "Continue to Payment and Review" (User is taken to payment and review page)
15. Keep all default selections and click "Place Order" (user will get an error saying "no such entity with orderId <order id>")

Below are most of the screenshots for every page. I missed the screenshot for the cart page the second time.

<img width="1430" alt="screen shot 2019-01-07 at 9 22 30 am" src="https://user-images.githubusercontent.com/5776197/50776983-0580d380-1260-11e9-9a02-65015d1f895f.png">
<img width="1440" alt="screen shot 2019-01-07 at 9 23 09 am" src="https://user-images.githubusercontent.com/5776197/50776984-0580d380-1260-11e9-8a33-ea334f2689ab.png">
<img width="1440" alt="screen shot 2019-01-07 at 9 23 41 am" src="https://user-images.githubusercontent.com/5776197/50776985-0580d380-1260-11e9-9de9-96f33c41762b.png">
<img width="1440" alt="screen shot 2019-01-07 at 9 23 55 am" src="https://user-images.githubusercontent.com/5776197/50776987-0580d380-1260-11e9-8c1f-257af725ae73.png">
<img width="798" alt="screen shot 2019-01-07 at 9 24 27 am" src="https://user-images.githubusercontent.com/5776197/50776988-0580d380-1260-11e9-9ce5-902ea8d51ff5.png">
<img width="1386" alt="screen shot 2019-01-07 at 9 25 17 am" src="https://user-images.githubusercontent.com/5776197/50776990-06196a00-1260-11e9-999c-027589831cfd.png">
<img width="1051" alt="screen shot 2019-01-07 at 9 25 26 am" src="https://user-images.githubusercontent.com/5776197/50776991-06196a00-1260-11e9-82e4-9cb13df5538d.png">
<img width="1440" alt="screen shot 2019-01-07 at 9 29 03 am" src="https://user-images.githubusercontent.com/5776197/50776993-06196a00-1260-11e9-998f-8b9c8ecf6b80.png">

<img width="1440" alt="screen shot 2019-01-07 at 9 29 47 am" src="https://user-images.githubusercontent.com/5776197/50777193-8fc93780-1260-11e9-8a99-3fa767a5056b.png">

<img width="1440" alt="screen shot 2019-01-07 at 9 31 43 am" src="https://user-images.githubusercontent.com/5776197/50777104-42e56100-1260-11e9-8231-ae5c57c74a88.png">

<img width="1186" alt="screen shot 2019-01-07 at 9 33 40 am" src="https://user-images.githubusercontent.com/5776197/50777084-39f48f80-1260-11e9-908c-58341a39c279.png">
<img width="941" alt="screen shot 2019-01-07 at 9 33 51 am" src="https://user-images.githubusercontent.com/5776197/50777085-39f48f80-1260-11e9-88ed-c210669130c3.png">
<img width="1423" alt="screen shot 2019-01-07 at 9 35 33 am" src="https://user-images.githubusercontent.com/5776197/50777086-3a8d2600-1260-11e9-95ff-02213a4bc5af.png">
<img width="1423" alt="screen shot 2019-01-07 at 9 35 46 am" src="https://user-images.githubusercontent.com/5776197/50777087-3a8d2600-1260-11e9-89f1-0ec2f589fecd.png">
<img width="1440" alt="screen shot 2019-01-07 at 9 36 10 am" src="https://user-images.githubusercontent.com/5776197/50777088-3a8d2600-1260-11e9-89e7-967f2cd3d2aa.png">

**Comment by tarishah** [comment] 2019-01-18 18:31
@shilpsauce We have already released a fix for this a while back. It's now merged into the master branch. Will you be able to update the Amazon Pay plugin to the latest version on the master branch. 

Please confirm if upgrading to the latest version resolves the issue.

Thanks,
Tarini

**Comment by tarishah** [comment] 2019-02-12 23:01
Closing this, as the issue no longer exists and banyan botanicals is live with Amazon Pay.

**Closed by tarishah** 2019-02-12 23:01 UTC

**Comment by yogeshkhasturi** [comment] 2020-05-19 15:31
Hi @tarishah Would you please share what was issue and where is the fix for that issue?


Thanks,

**Comment by christianzichichi** [comment] 2020-07-01 10:17
Hi @yogeshkhasturi , please update Amazon Pay plugin to latest version to solve the issue:

M2.2.x: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/2.1.x/PATCH_INSTRUCTIONS.MD
M2.3.x: https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD

Thanks
Regards

Christian
