### ISSUE TITLE
Mobile payments is not possible when Magento in production mode

### ISSUE THREAD

**Issue by balex13** [amzn/amazon-payments-magento-2-plugin#216] opened 2018-04-26 23:27 UTC
#### What I expected

It should be possible to use Amazon Pay on production mode.

JS compilation is enabled by default in Magento 2 production mode. 
Mobile device has touch screen so redirect is used.

#### What happened instead

After customer successfully logged in he redirected back to the store `processAuthHash` action. "You will be redirected shortly" message appears behind a spinner (processStart). But redirect never starts.

##### On server
Enable Production mode

##### On mobile device
1. Add any product to the shopping cart
2. Go to checkout
3. Press Amazon Pay button. Customer redirected to Amazon Login page
4. Enter correct login information. Customer redirected back to `processAuthHash` action
5. Page with spinner and "You will be redirected shortly" message appears. Redirect does not start. 
6. Check console log for JS error ```Uncaught Error: Module name "Magento_Ui/js/lib/registry/registry" has not been loaded yet for context: _. Use require([])```

#### Your setup

* Magento version: 2.1.6
* Amazon Pay Extension Version: 1.2.6
* Magento Edition: Enterprise Cloud
* JavaScript Console: 
![image](https://user-images.githubusercontent.com/7217592/39336146-ad2cc596-49be-11e8-8c7e-556409ca7c12.png)
* Shop URL : n/a

#### Additional info and possible hot-fix
It is not possible to remove `amazonPayment` property from `window`. Because it used in current version of `Widgets.js` and `login1.js` - these files on Amazon Pay side. And so it is present there despite it was moved to registry by **Extension now uses uiRegistry** feature. My comment here https://github.com/amzn/amazon-payments-magento-2-plugin/commit/d5d3d9fd72eaecfa15c2ed7000287a7c806b29cf#r28753669

##### Hot-fix: 
   1. Return back `amazonPayment` property to `window`. 
    2. Override amazon-widgets-loader.js and login-button-wrapper.js and correctly use dependency to uiRegistry. Or remove uiRegistry at all.

**Comment by BabliDey** [comment] 2018-05-25 07:11
Hello @balex13,
did you get any solution for this.. I am also having the same problem.

**Comment by lemked** [comment] 2018-05-25 09:48
Hi @BabliDey and @balex13 ,

I'm very sorry for not having answered this sooner. Our support agency is currently looking into this. We will provide an update soon.

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-05-28 12:08
Hi @BabliDey and @balex13 ,

We've got feedback from our support agency that the problem couldn't be reproduced with Magento 2.1.6, 2.2.3 or 2.2.4.

Can you please provide access to a staging environment per SSH where the problem can be reproduced? Please get in contact with us via payments-cp-devel@amazon.com regarding the access to the staging environment.

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-06-05 07:02
We've been able to reproduce the problem and are currently looking into this.

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-07-31 08:27
Hi @BabliDey and @balex13 ,

This issue should have been fixed by a change in our widgets.js library. Can you verify if you are still encountering this?

Kind regards,
Daniel

**Comment by suneet-magento** [comment] 2019-02-06 09:31
Hey @lemked, we are also getting the same issue on Magento Open Source 2.2.7. Can you please share the fix of this module?

We have installed v2.1.2.

**Comment by lemked** [comment] 2019-02-11 08:18
Hi @suneet-magento ,

We have double checked this and I can confirm that this issues is solved partially only. The problem still persists when using sandbox mode and redirect authentication (on product details pages and when using a mobile device).

Can you confirm that the issue that you are referring to is the redirect to the Amazon Pay checkout after login not working (so being stuck on the page that shows "You will be redirected shortly)?

Kind regards,
Daniel

**Comment by zsco** [comment] 2019-04-23 12:07
Hi @lemked,

I can confirm that the issue (being stuck on the page that shows "You will be redirected shortly) still persists. We just upgraded to Magento Version 2.2.8 using region "Eurozone". Also, the issue is also present in production mode in our case.

Regards

**Comment by lemked** [comment] 2019-04-23 14:01
Hi @zsco ,

Can you share the website where this is reproducible? If the website is not public, please share the required access information with us via payments-cp-devel@amazon.com.

Kind regards,
Daniel

**Comment by zsco** [comment] 2019-04-23 15:07
Hi Daniel,

please try https://test2856.handyhuellen-24.de/. 

Regards

**Comment by lemked** [comment] 2019-04-25 12:22
Hi @zsco ,

Can you disable the sandbox mode for the website mentioned above? That way we can test it in production/live mode.

Kind regards,
Daniel

**Comment by zsco** [comment] 2019-04-25 13:35
Hi @lemked,

please refer to https://www.handyhuellen-24.de/. It's in live mode and not working. Curiously, when switching to live mode on our test site, the rederect is working, so it may be a problem with JS compression.

Regards

**Comment by lemked** [comment] 2019-04-26 12:40
Thanks for confirming. Leaving this issue open until we have fixed this on sandbox as well.

**Comment by johnvanrees** [comment] 2019-04-29 22:09
I am having this same problem with Magento 2.2.8 and Amazon 2.1.3. The production, US region does not allow the mobile user to move past the "You will be redirected shortly" screen.

**Comment by tarishah** [comment] 2019-05-03 02:06
We are looking into this issue. I will provide an update as soon as I have one.

Thanks for reaching out. 
Tarini

**Comment by johnvanrees** [comment] 2019-05-10 17:57
When in private mode, the checkout loads fine. I think the issue is when the browser tried to use Amazon Checkout when it wasn't working or when used on the M1 integration. The problem only appears for the customers that have used the Amazon Checkout in the past and have not cleared their browser.

**Comment by tarishah** [comment] 2019-05-12 21:34
@johnvanrees Our team is looking into this and we should have a fix in next couple of weeks. I will update you once we have the fix released. 

Thanks,
Tarini

**Comment by hoangtuan21193** [comment] 2019-06-27 03:23
We stuck with same problem about 2 weeks, any update on this problem?
In my case, when user login, logout and login again, the "You will be redirected shortly" message appears and not redirect.

**Comment by tarishah** [comment] 2019-06-27 20:20
@hoangtuan21193 Magento 2.3.2 and 2.2.9 contains a short term fix for the issue you have mentioned. We are working on an ideal solution and should have the fix out sometime in late July. I will provide na update here once we roll out the patch.

Sorry for any inconvenience this may cause.
Tarini

**Comment by hoangtuan21193** [comment] 2019-06-28 01:53
@tarishah Thank you for your fast reply!
We are using Magento 2.2.8 and can not update to 2.2.9 right now.
Would you mind if I can have a link of commit about that short term fix for the issue.
Thank you so much!

**Comment by vincent-wantomo** [comment] 2019-07-03 00:50
We have the same issue on 2.2.9.
Only works on private mode or with a cleaned browser (safari, iOS). Desktop is working fine. Also, we're using the JPN region.

**Comment by hoangtuan21193** [comment] 2019-07-03 00:57
@vincent-wantomo seem like we have same problem, I’m trying to copy some js code from master branch. I will let you know if it work. Also, we’re are using JPN too.

**Comment by tarishah** [comment] 2019-07-03 02:04
@vincent-wantomo Apologies for the behavior you're running into. Can you please direct me to the site url the issue is on? Please email us at payments-cp-devel@amazon.com with the information. 

Thanks!

**Comment by nitin-bc** [comment] 2019-07-03 15:15
Hi @vincent-wantomo I am also facing exact same issue in Magento 2.2.7 with Amazon-pay version 2.1.2. My site URL is https://www.sfcable.com/. Earliest response would be highly appreciated. My site is already live and I am loosing the customers. Please help asap.

Thanks

**Comment by tarishah** [comment] 2019-07-03 20:50
@nitin-bc Thanks for reaching out. I was not able to locate Amazon Pay button at https://www.sfcable.com/.
However, we have already started looking into this issue. We will provide an update as soon as we have a fix ready to share.

Thank you for your patience.
Tarini

**Comment by vincent-wantomo** [comment] 2019-07-07 23:08
Hello,

Any updates regarding this issue ? Do you havean ETA for a fix?

It's very critical for all of us. It's unlikely that we'll let Amazon Pay activated on live servers if customers will get stuck on a redirect page. If we can help debugging by providing more information, we'll be more than happy to help.

Thank you in advance.

**Comment by tarishah** [comment] 2019-07-08 02:55
@vincent-wantomo We are looking into this issue. I should be able to provide an update by end of this week. 

Thank you for your patience.
Tarini

**Comment by lemked** [comment] 2019-07-12 06:55
Fixed in current master branch, will be available with next Magento 2 release.

**Comment by nitin-bc** [comment] 2019-07-12 06:59
Hi @lemked Thank for your response. Can I get commit number to implement this patch in my current website instead of waiting for new Magento release?

Thanks

**Comment by lemked** [comment] 2019-07-12 07:03
Hi @nitin-bc ,

Sure! Here you go: https://github.com/amzn/amazon-payments-magento-2-plugin/commit/18b88a4e1a5bcd4700b0d3a1dec011c05c37c643

Kind regards,
Daniel

**Comment by vincent-wantomo** [comment] 2019-07-13 04:18
Thank you for the fix.

However, could you give us a clear procedure to update from latest magento update (2.2.9/2.3.2) ? Master branch is the same for 2.2.x and 2.3.x ? 

We just **can't** wait for next magento 2 update as it's very critical. But the latest update of Amazon pay module is from April 5th, and this pull request is including some files that are not existing in 2.2.9 (src/Core/Model/AmazonConfig.php for example). 

Thank you in advance.

**Comment by vincent-wantomo** [comment] 2019-07-16 10:13
If 2.3.2 is on master, and 2.2.x is on 2.1.x, it means your patch is not available for Magento 2.2.x (Latest commit b2961b7  19 days ago) ?

Can we get any update soon please ?

**Comment by lemked** [comment] 2019-07-16 10:47
Hi @vincent-wantomo ,

We will prepare a patch file with update instructions and report back here.

Kind regards,
Daniel

**Comment by vincent-wantomo** [comment] 2019-07-18 08:50
Thank you Daniel. Do you have an ETA for this ?

Thank you in advance.

**Comment by lemked** [comment] 2019-07-19 12:33
**Update instructions for Magento 2.3.2**

1. Install the "composer-patches" tool via composer:  

```
composer require cweagans/composer-patches
```

2. Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.
```
        "patches": {
            "amzn/amazon-pay-and-login-with-amazon-core-module": {
                "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.2.9-3.2.11.patch"
            },
            "amzn/amazon-pay-module": {
                "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.2.9-3.2.11.patch"
            },
            "amzn/login-with-amazon-module": {
                "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.2.9-3.2.11.patch"
            }
        }
```
3. Install the patch via composer:
```
composer -v install
composer update --lock
```

4. Apply the change within Magento:

```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

**Comment by lemked** [comment] 2019-07-19 12:33
Update instructions for Magento 2.2.9 will follow soon.

**Comment by snoroozi** [comment] 2019-07-21 21:19
Just curious if Amazon pay will ever leave beta phase?

**Comment by tarishah** [comment] 2019-07-22 02:08
@vincent-wantomo We will have the update instructions for Magento 2.2.9 to share, by EOD tomorrow.

**Comment by tarishah** [comment] 2019-07-23 04:18
@vincent-wantomo, update instructions for Magento 2.2.9, are as below:

1. Install the "composer-patches" tool via composer:

`composer require cweagans/composer-patches`

2. Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.

        "patches": {
            "amzn/amazon-pay-and-login-with-amazon-core-module": {
                "2.2.14->2.2.16": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.2/amzn/amazon-pay-and-login-with-amazon-core-module/2.2.14-2.2.16.patch"
            },
            "amzn/amazon-pay-module": {
                "2.2.14->2.2.16": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.2/amzn/amazon-pay-module/2.2.14-2.2.16.patch"
            },
            "amzn/login-with-amazon-module": {
                "2.2.14->2.2.16": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.2/amzn/login-with-amazon-module/2.2.14-2.2.16.patch"
            }
        }
3. Install the patch via composer:
```
composer -v install
composer update --lock

```
4. Apply the change within Magento:
```
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

**Comment by kruegge82** [comment] 2019-07-23 07:48
i have install the patch, but the problem is not deleted on not mobile pages...

**Comment by lemked** [comment] 2019-07-23 08:08
Hi @kruegge82 ,

Can you provide a screenshot of the "intermediate" page? Please make sure the browser console is visible so that we can see debug/error output.

Kind regards,
Daniel

**Comment by kruegge82** [comment] 2019-07-23 08:19
<img width="1919" alt="Bildschirmfoto 2019-07-23 um 10 18 24" src="https://user-images.githubusercontent.com/6518148/61695173-52775380-ad33-11e9-8928-9e5d0f8cd6a9.png">

**Comment by lemked** [comment] 2019-07-23 10:23
Thanks for the screenshot @kruegge82 . Can you share details (URL, access credentials if required) with payments-cp-devel@amazon.com so that we can investigate the issue?

Kind regards,
Daniel

**Comment by vincent-wantomo** [comment] 2019-07-23 12:24
Thank you for the fix and procedure. The installation was successful. We are now testing on our staging servers and will give an update probably by tomorrow.

We faced some issues related to Japanese localisation : https://github.com/amzn/amazon-payments-magento-2-plugin/issues/233 (mainly because there's no city field in Amazon Japan, + no firstname/lastname, only one grouping both).

**Comment by lemked** [comment] 2019-07-23 14:57
Thanks @vincent-wantomo . I've provided feedback on the JP address issue in #233 .

**Comment by tarishah** [comment] 2019-07-24 23:00
@vincent-wantomo Were you able to test the redirect fix provided?

**Comment by vincent-wantomo** [comment] 2019-07-24 23:40
Yes it’s just deployed and working so far. I am still monitoring to see if there’s any issues for some customers and will reply back here if it’s the case.

Thank you !

**Comment by tarishah** [comment] 2019-07-25 05:23
@vincent-wantomo Glad to hear this! Please let us know if there are any issues.

**Comment by vincent-wantomo** [comment] 2019-07-25 12:38
So far, we did not get any report of issues by customer/customer service.

However, we got one reported issue internally. I was NOT able to reproduce by a standard customer journey but since it was internally, I got the intuition that I could come from previous testing and might be related to cookie domains that could be shared between test servers and live servers (test.xxxx.com / xxxx.com).

I was able to reproduce by the following scenario : 
1) Go on a test server (let's call it test.mywebsite.com) and checkout using Amazon pay.
2) After you're logged in and successfully redirected to the checkout page, you can switch to the live server by opening a new tab/window (let's call it mywebsite.com).
3) Checkout WITHOUT Amazon Pay, by using the standard checkout button.

Issue : 
Amazon Pay checkout will appear by default. It's impossible to switch to the standard checkout by clicking on the CTA "Return to standard checkout". It will try to switch but then it will redirect back to the Amazon Pay checkout. When trying to select address/go to payment a session error message will appear.

![session_timeout](https://user-images.githubusercontent.com/29086470/61874596-bceee600-af23-11e9-83c6-8dd785571174.png)

Here's the console log message : 

> OffAmazonPayments.Widgets.AddressBook BuyerSessionExpired セッションが時間切れになりました。購入者はウィジェットを読み込む前に、サインインしてください。Buyer's session with Amazon has expired. The buyer must sign in before you render the widget.

Even by login/out will not solve the issue. The only way to "solve" was to delete the cookies.

Again, it might be just a case related to cookies domain, but so far I have never experienced this with Amazon Pay before. We did not get this reported by a customer so far but it could be worth investigating a bit on your side just in case. The fact that the standard checkout is taken over by default by Amazon Pay is a bit scary, but might never happen in "real cases".

Let me know if it's better to create another ticket or if you need more details.

**Comment by islandskater43** [comment] 2019-07-26 16:56
@vincent-wantomo  - the [issue you are describing](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/216#issuecomment-515026810) is exactly what you mentioned, specific to an edge case involving our sandbox environment and our production environment.

The current version of the Amazon Pay Magento 2 extension uses the existence of an Amazon Pay buyer session to route the buyer to the Amazon Pay checkout flow, regardless of whether they click the Amazon Pay button. This is done to facilitate the fastest checkout possible. The Amazon Pay buyer session looks the same to the JS code, whether it is a sandbox session or a production/live session. When you click logout, the write/delete action is taken in the environment in which you are operating (sandbox in your test environment, production/live in your live environment).

So when you start a session in sandbox, then visit the live site, it is recognizing the sandbox session. Clicking the "Return to standard checkout" doesn't help as it only tries to log you out of the production/live session.

This should never be an issue with your real, external customers, unless they get to your test server, and then try and checkout within 1 hour before the session expires.

**Comment by vincent-wantomo** [comment] 2019-07-29 07:18
Ok, thank your for the details !

Also, so far, no reported issues with Amazon Pay with our customers (Magento v2.2.9).

**Comment by budoland-ab** [comment] 2019-08-16 11:31
> **Update instructions for Magento 2.3.2**
> 
> 1. Install the "composer-patches" tool via composer:
> 
> ```
> composer require cweagans/composer-patches
> ```
> 
> 1. Update the "extra" section in composer.json (or add it if it does not exist) with the module name, a patch description, and location of the patch to be applied.
> 
> ```
>         "patches": {
>             "amzn/amazon-pay-and-login-with-amazon-core-module": {
>                 "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-and-login-with-amazon-core-module/3.2.9-3.2.11.patch"
>             },
>             "amzn/amazon-pay-module": {
>                 "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/amazon-pay-module/3.2.9-3.2.11.patch"
>             },
>             "amzn/login-with-amazon-module": {
>                 "3.2.9->3.2.11": "https://raw.githubusercontent.com/bear-mmartin/patchmatrix/master/patches/Magento2.3/amzn/login-with-amazon-module/3.2.9-3.2.11.patch"
>             }
>         }
> ```
> 
> 1. Install the patch via composer:
> 
> ```
> composer -v install
> composer update --lock
> ```
> 
> 1. Apply the change within Magento:
> 
> ```
> php bin/magento setup:upgrade
> php bin/magento setup:di:compile
> php bin/magento cache:clean
> ```

Hello tarishah,

thank you for the update. I've a question regarding to your approach:

If I do the changes you asked me to do, will that affect any future update of magento? Will the changes in composer.json would be removed automatically the next time updating our system?

Kind regards,
Alex

**Comment by budoland-ab** [comment] 2019-10-15 07:36
@terishah did this patch make the M 2.3.3 release?

**Comment by lemked** [comment] 2019-10-25 05:37
@budoland-ab , yes, this was incorporated into M2.3.3 and 2.2.10. Can you confirm that the problem has been resolved for you? 

This should by the way make the patches provided in this thread obsolete, so they can safely be removed.

**Closed** 2020-01-14 15:43 UTC
Labels: ack, bug, waiting for release
