### ISSUE TITLE
Login section not rendering during checkout

### ISSUE THREAD

**Issue by jfain189** [amzn/amazon-payments-magento-2-plugin#275] opened 2018-07-05 20:21 UTC
#### What I expected
Login section to render properly

#### What happened instead
When you add an item to your cart and go to checkout with amazon pay enabled the whole login / provide shipping address section is missing.

#### Steps to reproduce the issue
Enable Amazon Pay in store configuration
Add item to cart
Go to checkout page

#### Your setup

* Magento version: 2.2.5
* Amazon Pay Extension Version: 1.2.6 & 2.0.14 (I tried both)
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
Error in console:
![js_console](https://user-images.githubusercontent.com/12579419/42346095-6cf067ac-806f-11e8-9336-45963a6fbc21.JPG)

* Shop URL : dev.precisiontools.com

Screenshot of problem:
![osc_broken](https://user-images.githubusercontent.com/12579419/42345985-19623da4-806f-11e8-9c3c-a124b8d75d94.JPG)

Expected Result (from production site):
![osc_working](https://user-images.githubusercontent.com/12579419/42345997-21fe3c7e-806f-11e8-98c1-0924e725736a.JPG)

**Comment by lemked** [comment] 2018-07-06 06:15
Hi @jfain189 ,

This is probably an issue caused by the custom theme. From the error message, I would guess that the knockout definitions of your custom theme and that of our extension are messing with each other.

Can you provide us access to the development system via SSH? Please provide the access credentials to the email address payments-cp-devel@amazon.com.

Kind regards,
Daniel

**Comment by jfain189** [comment] 2018-07-09 14:10
Hi Daniel,

I sent an email to that account. I am still awaiting a reply.

**Comment by lemked** [comment] 2018-07-09 14:44
Hi @jfain189 ,

I sent you a reply.

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-07-10 06:09
Looking into it

**Comment by lemked** [comment] 2018-07-11 14:32
Hi @jfain189 ,

The test site under https://dev.precisiontools.com currently throws a lot of 404 errors when rendering it. Can you fix these errors so that we can be sure that the reported problem is not a side-effect of something else?

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-07-23 09:15
Hi @jfain189 ,

We are still encountering a bunch of errors when browsing the test site. Could you verify and fix these so that we can start our investigation?

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-07-27 07:49
Closing this due to missing feedback. Please re-open the issue as needed.

**Closed by lemked** 2018-07-27 07:49 UTC
Labels: customer feedback required, needs investigation
