### ISSUE TITLE
Upgrade to 2.0.14 Doesn't Work

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-2-plugin#308] opened 2018-08-09 21:14 UTC
#### What I expected
For the upgrade to work

#### What happened instead

http://nimb.ws/cFrEdj

#### Steps to reproduce the issue

install magento 2.2.5 which came with 2.0.12 and try to upgrade the module via composer         "amzn/amazon-payments-magento-2-plugin": "2.0.14"

#### Your setup

thegreennursery.com community
2.2.5 mage

**Comment by lemked** [comment] 2018-08-10 08:11
Dear @snoroozi ,

Thank you for reporting this issue.

Can you please check if the problem can be solved by following the instructions in documentation, section "[Manual Composer Install Method](https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#manual-composer-install-method)"?

Please ensure to execute the commands for upgrading (setup:upgrade), dependency injection compilation (di:compile), deploying static content (setup:static-content:deploy xx_XX). You may also want to ensure that the caches are cleared (cache:flush).

Kind regards,
Daniel

**Comment by snoroozi** [comment] 2018-08-10 11:48
Yes, @lemked - that is what I've done twice without the ^ and set to 2.0.14 as the manual describes.  I have some experience in the area.

**Comment by islandskater43** [comment] 2018-08-10 17:30
Hey @snoroozi  - can you confirm you ran `composer update` and that your lock file also states `2.0.14`? I'm inferring that you did based on your statement above, but just looking for explicit confirmation.

Assuming your steps to reproduce were:
1. Install Magento 2.2.5
1. Run `composer require amzn/amazon-payments-magento-2-plugin:^2.0.14`
1. Run `composer update`

**Comment by snoroozi** [comment] 2018-08-11 11:56
I did not run composer update (not in manual), and my lock file shows .12 version

Will running composer update affect other extensions as well?

**Comment by snoroozi** [comment] 2018-08-14 11:14
@islandskater43 can I get an update on how to update please?

**Comment by snoroozi** [comment] 2018-09-04 15:39
@lemked still no resolution?

**Comment by lemked** [comment] 2018-09-05 06:08
Hi @snoroozi ,

We are currently looking into this. The problem is related to the bundled extension using a different naming schema than the version that we distribute via the GitHub repository.

Kind regards,
Daniel

**Comment by lemked** [comment] 2019-07-12 07:24
Closing as this should not happen anymore with recent versions of our extensions that are bundled with Magento 2. Please re-open if problem persists.

**Closed by lemked** 2019-07-12 07:24 UTC
Labels: ack, needs investigation

**Comment by snoroozi** [comment] 2019-07-24 21:37
I'm still facing this. Now I'm on Magento 2.30 and can't update to the latest Amazon pay. Please describe steps.

**Comment by lemked** [comment] 2019-07-25 06:52
Hi @snoroozi ,

Can you confirm that you are on version 3.0.0 of our extension? We can provide you a patch set for updating to the latest version of the extension.

On the long-term, manual patching will no more required as it will be possible to update the extension via the regular composer update mechanism. This is currently being worked on as there are certain limitations around this for Core Bundled Extensions.

Kind regards,
Daniel

**Comment by snoroozi** [comment] 2019-07-25 11:43
@lemked yes, I'm on 3.0.0  - I didn't see your reply and opened a new issue this morning with screenshots.

https://github.com/amzn/amazon-payments-magento-2-plugin/issues/533
