### ISSUE TITLE
Issue with removing addresses linked to Amazon

### ISSUE THREAD

**Issue by Silarn** [amzn/amazon-payments-magento-2-plugin#53] opened 2017-04-18 21:59 UTC
This may be a Magento 2.1.6 issue, but I'm not sure.

#### What I expected

After editing my account addresses on the front-end (removing duplicates and consolidating), I tried to check out via the normal Magento checkout (not using Amazon).

I assumed I would proceed normally to the payment step.

#### What happened instead

I found that I would be redirected to the customer settings screen when I tried to advance to the payment step.

Checking with the response data in the AJAX call, it returned an error stating essentially that there was a problem connecting with the Amazon API (unfortunately I didn't copy the error).

I was able to fix the problem by initiating checkout by logging into Amazon again. This apparently fixed whatever data issue was causing the problem.

#### Steps to reproduce the issue

I haven't tried to repeat it yet, but I assume the steps will be as follows:

During the order or within the account screen, edit your addresses - adding new addresses and deleting old ones.

Try to check out (without using Amazon).

#### Your setup

* Magento version: 2.1.6
* Magento Edition: Community
* Shop URL : https://www.smithbuy.com

I will attempt to debug this more in the future, as time allows, however I'm not sure how long that will be.

**Comment by Silarn** [comment] 2017-04-20 07:09
This __may__ be related to another module. I'm also seeing some intermittent ajax load errors when initiating checkout steps. Either it's 2.1.6 or another module.

I'll try disabling a couple and see what happens.

**Comment by danielneu** [comment] 2017-04-20 08:53
Thanks a lot,

our support agency is also looking into this.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-05-09 12:02
Hi @Silarn 

we are not able to reproduce this issue on different M2 versions.
Are yous till experiencing this issue? Are you in the meantime sure this is related to the Amazon Pay module?

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-05-22 11:33
@Silarn 

I would love to go on with this one, could you kindly check my previous comment and add information which helps us to understand if this is related to our module or not?

Best wishes 
Daniel

**Comment by Silarn** [comment] 2017-05-22 19:09
Sorry, I've not yet been able to replicate this issue. If it does happen again, I'll try to document it as well as possible. I'll just go ahead and close this for now.

**Comment by Silarn** [comment] 2017-07-17 18:43
I think this may be due to having an account tied to a live Amazon account and then trying to use the Amazon sandbox.

It gets into a strange state where trying to advance to the payment/billing step instead redirects to the user account screen. However, I believe logging in with a valid sandbox account corrects the problem.

**Comment by danielneu** [comment] 2017-07-18 07:02
Hi,

you will not be able to sign in with a production buyer account in sandbox.
In your initial request you said, logging in with Amazon again fixed it.

If the account was created for a live amazon customer and you are now in sandbox, the login would not work (unless you create a sandbox account using the email of a production customer account?)

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-08-31 09:51
Hi,

closing this one again, as it seems to be something which will only happen for developers (sandbox and live sessions that mix) and in favor of an improved handling where to redirect to #120 

Thanks
Daniel

**Closed by danielneu** 2017-08-31 09:51 UTC
Labels: ack, customer feedback required, needs investigation
