### ISSUE TITLE
Wrong import of address data from amazon if only one address field is enabled in Magento

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#103] opened 2017-08-17 12:26 UTC
There is a wrong import of address data from amazon if only one address field is enabled in Magento.
Then the second line of the address is transferred to magento but can not be edited when magento2 is set to "one line address field".

I suggest that the extension checks how many address fields are activated in magento (1,2 or3) and if only one field is activated the address data from the amazon address needs to be merged into one line. etc.

**Comment by andidhouse** [comment] 2017-08-31 08:20
Hello?

**Comment by danielneu** [comment] 2017-08-31 09:47
Hi,

can you hint me to the location of this setting?
I will hand it over for investigation then. Sorry for missing this one.

Best wishes 
Daniel

**Comment by andidhouse** [comment] 2017-08-31 09:50
Hi Daniel,

in the Magento2 system you have a option in the backend which defines the rows of the address line.

This can set to 1 row, 2 rows or 3 rows.

So if one row is selected in the magento2 backend and the address in the amazon user account has for example 2 or 3 rows this bad behavior happens.

So in case 1 row is active in the magento2 backend your extension should merge all address data from row 1,2 and 3 in the amazon account to one row.

Hope this is clear?

Thanks!

**Comment by danielneu** [comment] 2017-08-31 09:53
Makes thanks, thanks you.

I will hand this over now to get this corrected.

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-09-01 06:39
Hi,

we are unable to reproduce any issue with this setting changed.

![changed_number_of_lines](https://user-images.githubusercontent.com/10086275/29958045-05eb6e96-8ef1-11e7-9b25-60f32c780209.png)

![selected_address](https://user-images.githubusercontent.com/10086275/29958060-17d5752a-8ef1-11e7-8dbf-4dacff0d91f6.png)


![address_in_checkout_for_1_line](https://user-images.githubusercontent.com/10086275/29958049-0ac5b930-8ef1-11e7-9074-1f6a21e4fa8e.png)

![address_in_admin_for_1_line](https://user-images.githubusercontent.com/10086275/29958053-0e7a9eb0-8ef1-11e7-842b-ff40d1464d03.png)

**Comment by andidhouse** [comment] 2017-09-01 07:29
HI Daniel,

as far as i can see this is correct to reproduce the issue- but the problem is now if you click on "edit shipping adresse" there is only one line of the address shown in the magento backend (as it is set to 1 line of course). But the extension fills two lines in the address field (which are visible here in your screen) but the second line can not be edited in the magento backend.

Could you check and post a screen of the site after hitting the "edit" shipping address button?

Thanks!

**Comment by danielneu** [comment] 2017-09-01 08:06
Hi,
thanks for the additional details. We are able to reproduce and investigating now.

Best wishes 
Daniel

**Comment by RayAnaya** [comment] 2020-01-25 02:08
I am going to go ahead and close this issue, as we have had numerous upgrades and new versions since its original report.  Please feel free to re-open this issue if you still encounter problems using the latest version of Magento 2 and the Amazon Pay plugin.

**Closed by RayAnaya** 2020-01-25 02:08 UTC
Labels: ack, enhancement
