### ISSUE TITLE
getAmazonOrderReferenceId double call in ConfirmOrderReference plugin on quoteExtensionAttributes

### ISSUE THREAD

**Issue by daniel-ifrim** [amzn/amazon-payments-magento-2-plugin#926] opened 2020-10-30 07:10 UTC
#### Your setup

* Magento version: 2.3.5x
* 3.4.1-p2
* Magento Edition: Community
* running Amazon Payment in sandbox env without URLs whitelisted.
* on shipment step

In current version of the extension (4.1.1 / master branch), I see `getAmazonOrderReferenceId` doubled.

_Just asking if it Is correct._

https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/src/Payment/Plugin/ConfirmOrderReference.php#L107-L109
I do get an error on "set-payment-information" AJAX request:
```
Uncaught Error: Call to a member function getAmazonOrderReferenceId() on null in 
vendor\/amzn\/amazon-pay-module\/Plugin\/ConfirmOrderReference.php:109\nStack trace:\n

#0 vendor\/magento\/framework\/Interception\/Interceptor.php(146): Amazon\\Payment\\Plugin\\ConfirmOrderReference->afterSet(Object(Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor), '41', '83', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor))\n
##1 vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('83', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor))\n
##2 generated\/code\/Magento\/Quote\/Model\/PaymentMethodManagement\/Interceptor.php(26): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->___callPlugins('set', Array, Array)\n
##3 vendor\/magento\/module-quote\/Model\/GuestCart\/GuestPaymentMethodManagement.' in 'vendor\/amzn\/amazon-pay-module\/Plugin\/ConfirmOrderReference.php' on line 109
```

**Comment by christianzichichi** [comment] 2020-11-02 11:29
Hi @daniel-ifrim ,
this seems a duplicate of : https://github.com/amzn/amazon-payments-magento-2-plugin/issues/685
for Magento 2.3.5 and AP 3.4.1-p2, the latest AP version is 3.7.1 (4.1.1/master branch is for M2.4.x magento branch). In order to update to 3.7.1 and solve the issue, please use these instructions: https://gist.github.com/christianzichichi/aafb15d6aa397cdf17c3a2e832ece0fb

Thanks
Best
Christian

**Closed by christianzichichi** 2020-11-02 11:29 UTC
