### ISSUE TITLE
Checkout Place Order redirect to the cart on success

### ISSUE THREAD

**Issue by uabassguy** [amzn/amazon-payments-magento-2-plugin#559] opened 2019-09-17 02:42 UTC
#### What I expected

Customer sees the order success page when placing an order

#### What happened instead

Order is placed successfully, using the placeOrder method, we can see last_success_quote_id is set in the session during this request, but when redirect to onepage/checkout/success controller occurs, the checkout session is unset with DepersonalizePlugin, so the user is then redirected to cart. The order is placed in Magento and the success email is still sent.

#### Steps to reproduce the issue

Checkout with amazon pay on Magento 2.3.2 with full page cache enabled

#### Your setup

* Magento version: 2.3.2
* Amazon Pay Extension Version: 3.2.9
* Magento Edition: Enterprise
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : site is not live yet

![amzn-pay-redirect-issue](https://user-images.githubusercontent.com/3016166/65007122-ff94c500-d8b9-11e9-9ab6-1e26b049d90b.png)

**Comment by lemked** [comment] 2019-09-18 15:38
Thanks @uabassguy, we will look into it.
For reference, can you list any 3rd party extensions that you are using as part of the checkout?

Kind regards,
Daniel

**Comment by uabassguy** [comment] 2019-09-20 00:30
Just tested on vanilla 2.3.2 community and could not reproduce. Will review internally and reopen when I have more details.

**Comment by uabassguy** [comment] 2019-09-20 02:28
Issue is reproducible on Enterprise 2.3.2 with redis enabled.

Steps to reproduce:
Install magento enterprise 2.3.2
Install sample catalog
Enable redis in env.php config
Configure amazon sandbox with credentials
Checkout with amazon pay sandbox account as guest or logged in

Result:
redirected to cart instead of success page

**Comment by uabassguy** [comment] 2019-09-24 14:58
Some more information on this, it appears the 2nd checkout and after on vanilla works after the session is created, but if garbage collection kicks in and the server side session is wiped (or if redis is restarted and does not have persistence). Basically I was able to reproduce this when magento has to create the server side session.

**Comment by lemked** [comment] 2019-09-30 07:16
Thanks @uabassguy for providing detailed information. This will definitely make the analysis easier.

**Comment by livvly** [comment] 2019-10-03 05:29
Also running into this issue, having the exact condition besides Im on 2.3.2 Community version. Is there any update on this?

**Comment by uabassguy** [comment] 2019-10-04 21:00
I got word back from Magento support on this, since it was reproducible on Commerce and OS. They recommended changing the env.php config for redis sessions, specifically these 2 values:
'disable_locking' => '1',
'max_concurrency' => '20',

Looks like it resolved it from my testing

**Comment by livvly** [comment] 2019-10-08 20:08
I actually turned off redis and it's still happening to me. Amasty did some testing for me, and it also happened when then activate on a fresh 2.3.2 Magento install. Please advice

**Comment by lemked** [comment] 2019-10-09 06:21
Thanks for the feedback @livvly. Is there a Magento instance that you can provide us access to for reproducing the issue? If so, please send the credentials to payments-cp-devel@amazon.com and drop us a note here.

Kind regards,
Daniel

**Comment by livvly** [comment] 2019-10-09 19:59
Sent

**Comment by lemked** [comment] 2019-10-10 06:59
Hi @livvly ,

We received the URL for the test system and credentials, but it doesn't seem to point to a test system but live system instead.

Kind regards,
Daniel

**Comment by livvly** [comment] 2019-10-10 08:17
Hello there, I’m not sure what you meant by that. My site is still under development, and amazonpay is in sandbox mode still.   
  

  
  

  
  
>

**Comment by uabassguy** [comment] 2019-10-10 18:35
In our case it was sessions being locked sometimes when session is written, and sometimes not. So the last_success_quote_id is sometimes not written, and is a core issue, in which Magento support recommended to disable the session locking in redis. As far as files, I did not experience this behavior. I have also seen this affecting other payment methods which use the placeOrder method then redirect to cart after. Not sure if there is a better way to do it.

**Comment by livvly** [comment] 2019-10-10 18:40
We already did with the 2 lines you provided earlier. [https://prnt.sc/phl8w7](https://prnt.sc/phl8w7)
But still, we're getting redirected back to /checkout/cart

**Comment by KrzysztofMoskalik** [comment] 2019-10-22 10:09
I'm experiencing the same issue. I've made an investigation and looks like all bad things starts when i am rendering CMS Block in my custom (overwritten default magento) email footer html template. Not finish investigation yet but i believe this is related with some caching issue/logic.

**Comment by shilpambb** [comment] 2019-10-22 14:06
I'm running into the same issue. We have a very temporary fix until we have a proper fix. The diff is here: https://gist.github.com/shilpambb/54863f81853394f741b61d75f45d48c8

**Comment by lemked** [comment] 2019-10-24 12:27
Thanks for all the feedback. We will look into this and report back here as soon as possible.

**Comment by friendscottn** [comment] 2019-12-04 00:09
This happens if you add a {{block}} directive to your order confirmation email template. Then way down in vendor/magento/module-page-cache/Model/Layout/DepersonalizePlugin.php the session gets wiped out when the block directive is getting rendered. The sending of the order confirmation email ends up rendering the block directive which ends up killing the session. Then when the user gets redirected to the order confirmation page the session is gone so the user gets automatically redirected to the empty cart page.

**Comment by perfpcs** [comment] 2019-12-20 07:52
@shilpambb I can't thank you enough!! We have spent days on this problem and getting very aggravated! Your fix works like a gem! Thank you much Sir!!!!

**Comment by RayAnaya** [comment] 2020-01-27 18:26
Thank you all for your patience, as well as all of the information you've provided us!

We are introducing a fix for this in the next version of our plugin, bundled with Magento version 2.3.5.

**Comment by christianzichichi** [comment] 2020-02-12 14:40
Hi all,

Thank you all for your patience. The fix for this issue has been provided in this PR: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/598
it will be included in the next Magento release (2.3.5) and you can already find it in the latest release of our plugin (3.4.0) here: https://github.com/amzn/amazon-payments-magento-2-plugin

Regards

Christian

**Closed by christianzichichi** 2020-02-12 14:40 UTC
Labels: ack, bug, waiting for release

**Comment by dimikl1** [comment] 2020-02-18 12:57
> This happens if you add a {{block}} directive to your order confirmation email template. Then way down in vendor/magento/module-page-cache/Model/Layout/DepersonalizePlugin.php the session gets wiped out when the block directive is getting rendered. The sending of the order confirmation email ends up rendering the block directive which ends up killing the session. Then when the user gets redirected to the order confirmation page the session is gone so the user gets automatically redirected to the empty cart page.

The real MVP!! Thank you man

**Comment by pisarkov** [comment] 2023-08-03 13:01
> I got word back from Magento support on this, since it was reproducible on Commerce and OS. They recommended changing the env.php config for redis sessions, specifically these 2 values: 'disable_locking' => '1', 'max_concurrency' => '20',
> 
> Looks like it resolved it from my testing

Changing disable_locking to 1 solved the issue for me.
