### ISSUE TITLE
Switch to production mode not possible after upgrade to Magento 2.2.4

### ISSUE THREAD

**Issue by achatpc** [amzn/amazon-payments-magento-2-plugin#220] opened 2018-05-03 15:33 UTC
Preconditions
Magento 2.2.4
PHP 7.1
Ubuntu 17.04
Steps to reproduce
php bin/magento setup:di:compile

Expected result
Compilation complete
Actual result

![error](https://user-images.githubusercontent.com/17496183/39586741-1ce299ae-4ef8-11e8-9e50-1ec2c8be3b83.png)

LOG FILE:
main.CRITICAL: Source class "\amazonClient" for "amazonClientLogger" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class "\amazonClient" for "amazonClientLogger" generation does not exist. at /var/www/html/vendor/magento/framework/Code/Generator.php:185, RuntimeException(code: 0): Source class "\amazonClient" for "amazonClientLogger" generation does not exist. at /var/www/html/vendor/magento/framework/Code/Generator.php:185)"} []

Thank you in advance

**Comment by aholovan** [comment] 2018-05-11 09:34
Hi guys, 
As a quick fix I was able to get it working without errors by renaming definitions to amazonClientLoggerHandler and amazonIpnLoggerHandler respectively but seems a roots of the issue more deeper.

**Comment by aredridel** [comment] 2018-06-01 13:53
This is affecting us as well.

**Comment by MicheleBeargroup** [comment] 2018-06-01 18:09
Can you check to see which version of the Amazon Pay module you have? 2.2.4 now comes bundled with it and on composer update should give you version 2.0.7.  I ran compile on both 7.0 and 7.1 and was not able to reproduce the issue with a clean updated 2.2.4 install (see images).
 
![compilephp7 0](https://user-images.githubusercontent.com/5881429/40856296-9fc43ba4-6594-11e8-9d11-70caa6704e3d.PNG)
![compilephp7 1](https://user-images.githubusercontent.com/5881429/40856297-9fdcf1bc-6594-11e8-8c95-080422683c1e.PNG)

Also 2.0.7 is significantly different from 1.2.6 so it's possible if another version is overlapping the old one there might be conflicts.

**Comment by aredridel** [comment] 2018-06-01 21:13
2.0.4 for me

**Comment by MicheleBeargroup** [comment] 2018-06-01 22:31
Are you able to try:

composer update

see if 2.0.7 comes over

if so, then do
php bin/magento setup:update

then run di compile?

**Comment by islandskater43** [comment] 2018-06-05 16:22
@aredridel - any chance you were able to follow Michele's recommendation?

**Comment by aredridel** [comment] 2018-06-05 21:02
Will do shortly when I get a chance!

**Comment by islandskater43** [comment] 2018-06-28 00:13
Hi @aredridel - any chance you were able to take a look?

**Comment by lemked** [comment] 2019-07-12 07:29
Closing due to missing feedback. Please re-open if problem persists.

**Closed by lemked** 2019-07-12 07:29 UTC
Labels: customer feedback required
