### ISSUE TITLE
No option to pay with Amazon at checkout Step 2

### ISSUE THREAD

**Issue by cosmointeractive** [amzn/amazon-payments-magento-2-plugin#68] opened 2017-06-19 15:43 UTC
In you bypass the Amazon Pay button (in checkout process at Step 1) by clicking Next to continue checking out (Step 2) - there isn't an option for using Amazon Pay at that point.

#### What I expected

To still have the option to checking out with Amazon (maybe the button can redirect to step 1?)

#### What happened instead

There isn't an option to checking out unless another payment method exists.

#### Steps to reproduce the issue

1. Add product to cart 
2. Don't select pay with Amazon and click continue to checkout

#### Your setup

* Magento version: 2.1.5
* Magento Edition: Community
* Shop URL : https://goodtwice.com

**Comment by danielneu** [comment] 2017-06-21 12:38
Hi,

thanks for raising this with us. 

This is the intended behavior by Amazon Pay. We will vet options to add Amazon Pay to this step in a customer friendly way. I will close this as working as expected for now.

**Closed by danielneu** 2017-06-21 12:38 UTC
