### ISSUE TITLE
Amazon Pay button redirect issue

### ISSUE THREAD

**Issue by erravi62** [amzn/amazon-payments-magento-2-plugin#279] opened 2018-07-12 04:53 UTC
I have been using using your extension in Magento 2.1 site but the issue I am facing is that on checkout page when it displays the Amazon Pay button I click it and a pop up opens. So after logging in with the credentials it redirects me to the customer login page. But it should rather stay on the checkout page.
Please provide me a solution regarding this.
Thankyou

**Comment by lemked** [comment] 2018-07-13 11:53
Hi @erravi62 ,

Thank you for reporting this? To ensure that we have the minimum of required information to investigate this issue, can you please follow the template for creating issues when clicking the "[New issue](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/new)" button? This will ensure that we have version information, steps to reproduce, logs, screenshots and so on.

Kind regards,
Daniel

**Comment by erravi62** [comment] 2018-07-17 10:09
Hello,
       The problem still exist when I login using Amazon Pay Button and I have not logged in the website. After the Login with Amazon, it redirect to the website login page. But it should stay on the Checkout Page. Also please let me know if my settings are incorrect.  Please check this issue.

**Comment by lemked** [comment] 2018-07-17 11:41
Hi @erravi62 ,

As explained before, we will require some more information in order to investigate this issue. Please click  [this link](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/new) to see which information is required at a minimum.

Unfortunately, the video is also not very helpful and the URL you have provided points to our Indian retail website. Could you please review this?

Kind regards,
Daniel

**Comment by erravi62** [comment] 2018-07-17 12:21
Please check in this new video
https://drive.google.com/file/d/1YRQf-CX9VFOpRHBDyzaLb2jrTN0XsnSr/view

**Comment by erravi62** [comment] 2018-07-20 07:43
Hi there 
Any luck regarding this.
If you can kindly check the attached video everything will be clear.
Please update ASAP

**Comment by erravi62** [comment] 2018-07-23 06:20
Hi @lemked can you please update regarding the issue. I've stucked to this issue now

**Comment by lemked** [comment] 2018-07-23 09:45
Hi @erravi62 ,

The "Allowed Return URLs" was missing in your Seller Central account, which could have caused this issue. I see also several JS error in the browse console, that may cause our extension to fail. The Amazon Pay button is also missing on the cart page, which is probably caused by missing static content. 

Can you please deploy the static content for the website as described in our documentation?
https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#manual-composer-install-method

If done correctly, there should be a amazon-button.js available in the website sources as shown in the screenshot below.
 
![image](https://user-images.githubusercontent.com/4786477/43069623-e044db78-8e6d-11e8-8420-7eb792afee92.png)

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-09-25 07:34
Hi @erravi62 ,

Can you please provide an update whether you are still encountering an issue with our extension?

Kind regards,
Daniel

**Comment by lemked** [comment] 2018-12-14 08:00
Closing due to no further feedback. Please re-open if still occurring.

**Closed by lemked** 2018-12-14 08:00 UTC
Labels: customer feedback required
