### ISSUE TITLE
Cant save configuration (Failed to enable Amazon Pay: Please provide a Private Key)

### ISSUE THREAD

**Issue by JustADude-86** [amzn/amazon-payments-magento-2-plugin#1100] opened 2022-01-17 11:27 UTC
#### What I expected

I expect that once the appropriate data was input into configuration and the fields were populated and then the save button has been pressed the message "You saved the configuration." would appear and with that, the button and payment option would appear on the front-end and buyers can pay via Amazon-Pay.

#### What happened instead

Once saved manually or Automatically via AutoKey Exchange two conflicting messages appear:
1, Failed to enable Amazon Pay: Please provide a Private Key
2. You saved the configuration.

The message "One or more of the Cache Types are invalidated: Page Cache, **Configuration.**" appears and once cleared the button appears on the Frontpage but once clicked the message "Amazon pay is not set up on this ...." appears (on Amazon Pay website)".

The config at first glance appears to be saved but as soon as you press the button "Save Config" (on Sales => Payment Methods) the "Enable Amazon Pay" switches from "Yes" to "No".. (by its self).
#### Steps to reproduce the issue

1. Press the "Register or Connect an Amazon Pay Account" button
2. Proceed with steps and on the final step (where Keys are transmitted) close the windows
3. The message "Updating your config with new keys, please wait..." appears and the page reloads.
3. The page reloads and the two "conflicting" (saved and error) appears.

#### Your setup

* Magento version: 2.4.3-p1
* Amazon Pay Extension Version: 5.9.1
* Magento Edition: Community
* JavaScript Console: No error, no log.
* Shop URL : https://sandstrahlen.biz/

**Comment by sgabhart22** [comment] 2022-01-18 14:39
Hello @JustADude-86 , do you still see the same behavior with Auto Key Exchange after clicking the 'Reset account registration/configuration' button? Also interesting that the Amazon Pay button will display but lead to error messages once clicked; would you happen to have a staging site where we could see some of this behavior? We can add you to our internal ticket in order to continue the discussion.

**Comment by JustADude-86** [comment] 2022-01-18 15:03
@sgabhart22 Thank you for your reply. Yes, I tried the following:
- Reset (uninstall and re-install the module)
- Upgrading module (from older version to the new 5.9.1)
- Upgrading Magento from 2.4.3 to 2.4.3-p1
- Reset account registration/configuration button,..

No matter what version (Magento or module) or any combination Im still facing the same issue.

I can make a staging "copy" version of the current site if necessary in the next day or two if necessary.

And yes, I agree it seems very strange, it looks like Auto Key Exchange puts this configuration in some strange semi/saved state, but as soon as you reload or save config again the config gets reset back to "lease provide a Private Key" state.

**Comment by sgabhart22** [comment] 2022-01-18 22:01
@JustADude-86 I was finally able to reproduce this after wiping all of my Amazon credentials from all stores. It looks like when we are displaying the text area for Private Key in our configuration section, we are only checking the default store scope to see if there is a value for 'payment/amazon_payment_v2/private_key'. If there is, then we populate the field correctly, but if not, we continue to display the Copy & Paste/Upload .pem file buttons.

Watching the core_config_data table while stepping through the Auto Key Exchange process shows that all the values are being transferred from Amazon correctly, but we are being prevented from saving the config values in the admin section because the private key field is not being populated correctly. For now, you should be able to work around this by first saving Amazon Credentials for your default config, then trying AKE again for the store in question. We'll work on a more permanent fix for an upcoming release.

Please let us know if this works for you!

**Comment by JustADude-86** [comment] 2022-01-19 11:23
@sgabhart22
1. Via phpMyAdmin I have deleted (wiped) data from all Amazon-Pay related fields. 
2. I have selected Default Scope (like before)
3. With AKE I have connected to amazon pay and the transfer key was ok and only the "You saved the configuration" message appeared
4. I have cleared the Cache
5. And configuration saved without any issues and even after another "Save config" press of a Button the configuration is saved and "stable" :)

**But!** And there is a big BUT ;)
Now I'm facing another issue; => Express Checkout Button works and appears but Amazon Pay is not visible under Payment Methods and there is no way you can checkout if you use Amazon pay in the current configuration as Magento says there are no payment methods available currently (even if you Press Express Checkout Amazon pay button and Magento gets the data from amazon like Adress, ..etc).

We are using One Checkout module from Amasty but even if we disable it and go with a stock Magento checkout the issue pressists.

I have don't all the necessary c:c, c:f, i:reindex,.. but still no fix.
If you want me to open another "case" let me know.

**Comment by sgabhart22** [comment] 2022-01-19 16:01
@JustADude-86 Sounds like good progress!

There is currently a known issue with the one-step checkout module from Amasty displaying the Amazon Pay button at checkout. However, that issue is centered around the Pay Now button in the payment methods (not Express Checkout), so there may be another conflict here. And address population/payment method display should certainly work fine with a standard Magento checkout.

If you can successfully login with Amazon and have your shipping information populated at checkout, it sounds like the module is configured correctly for the most part. Perhaps an unintended side effect of clearing Amazon-related config values through phpMyAdmin? If you could check the Amasty menu from your admin panel for an option titled something like **Shipping & Payment by Customer Groups > Payment Methods**, you may simply need to enable Amazon Pay for all customer groups again. We had a similar sounding issue once upon a time.

If this option is unavailable or otherwise doesn't solve the issue, please let me know and we can create a new ticket for you. It seems like the original problem has been solved/worked around for now.

**Comment by JustADude-86** [comment] 2022-01-20 08:00
@sgabhart22 I feel stupid now :D.
You were 1000% correct. We have "Shipping & Payment by Customer Groups" from Amasty but completely forgot about when enabling new Payment you need to select all the groups you want this payment to be enabled for.

Thank you. You can close this thread because this issue is at least for me now resolved. Thank you again.

**Comment by sgabhart22** [comment] 2022-01-20 12:25
@JustADude-86 Please don't feel stupid, it doesn't take many Magento extensions on your installation before it's a lot to keep up with!

Very glad we could work it out, we'll close this issue for now but keep our internal ticket open to track the fix for the root problem you discovered.

**Closed** 2022-01-20 13:29 UTC
