### ISSUE TITLE
Cannot save preferences in Backend

### ISSUE THREAD

**Issue by joergmaertin** [amzn/amazon-payments-magento-2-plugin#333] opened 2018-08-29 10:50 UTC
Installed amazon pay 1.2.7 via composer. Amazon Pay is the only third-party payment method. I want to edit preferences and save.

Saving preferences should be possible

Clicking on "Save Config" in Backend in Sales-Payments does not work, no effect.

Installed Amazon Pay via composer
Amazon Pay is the only third party payment plug in
Go to backend
Insert necessary preferences for Amazon Pay
Button Save Config does nothing
no error messages

#### Your setup

* Magento version: 2.1.14
* Amazon Pay Extension Version:  1.2.7
* Magento Edition: Community
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL :

**Comment by lemked** [comment] 2018-08-29 13:46
Hi @joergmaertin ,

Can you please reload the configuration page in the back-end and try again to save the settings? This issues was observed on rare occasions and we couldn't reproduce it yet in a reliable way - refreshing the page did however usually solve the problem. 

Kind regards,
Daniel

**Comment by joergmaertin** [comment] 2018-08-29 16:15
Sorry, reloading doesn't help. But maybe I have a clue for you where to look:
I found out that latest Firefox and Safari on Mac have this error (save config not possible). I tried Chrome and it worked, saving config is possible. Would be nice though if it would work in any browser though.
I also excluded any incompatibility with another Magento extension by deactivating all third party extensions. No success.

**Comment by lemked** [comment] 2018-08-29 16:39
Thanks @joergmaertin , we will look into it.

**Comment by Ctucker9233** [comment] 2019-04-15 22:59
@lemked I just ran into this same problem with a magento 2.2.8 install. A json error gets thrown that seems to freeze the save config. It's unfortunately very vague but it reads "unexpected end of json input".

**Comment by lemked** [comment] 2019-04-17 15:42
Hi @Ctucker9233 ,

We couldn't reproduce this issue with any of the more recent versions of our extension (Magento 2.2.7 and higher). Can you please double check if the JSON that you have copied from Seller Central is properly formatted and not cut off?

Please DO NOT share the JSON string here as this contains the secret key of your merchant account.

Kind regards,
Daniel

**Comment by Ctucker9233** [comment] 2019-04-18 23:57
@lemked I haven't copied any JSON from Seller Central, so I don't know what you mean. This is simply the extension version that got shipped with 2.2.8. I am currently not using the Amazon Payments functionality, but simply having the module enabled causes this behavior.

**Comment by lemked** [comment] 2019-04-19 06:56
Hi @Ctucker9233 ,

Sorry for the misunderstanding. I was assuming that you are trying to configure the extension.

Can you double check if you did not accidentally insert any content into the ["Credentials JSON" field](https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#credentials-json) of our extension? Please also remove any contents from any other configuration fields of the extension and ensure that the ["Enable Amazon Pay"](https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#enable-amazon-pay) and [Enable Login with Amazon](https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#enable-login-with-amazon) are set to "No" as you are not using the extension anyway.

Kind regards,
Daniel

**Comment by Ctucker9233** [comment] 2019-04-20 16:21
@lemked No content in the credentials field or any other field. And login and pay are set to "no". The behavior still exists.

**Comment by lemked** [comment] 2019-04-23 06:35
Hi @Ctucker9233 ,

Can you provide a screenshot of the error message here? Please ensure that there is no confidential information contained in the screenshot before posting it.

Please also check if there any log files reporting this issue. A strack trace or similar error information would certainly be helpful to analyze the issue.

Kind regards,
Daniel

**Comment by RayAnaya** [comment] 2020-01-25 03:13
Hello all,

As we still cannot reproduce this, even with fresh installations - I am going to have to go ahead and close this issue for now.  If you are able to provide any screenshots or logs, we would be glad to help you troubleshoot further - but at this point, we would also recommend upgrading your magento installation to the latest version.

**Closed by RayAnaya** 2020-01-25 03:13 UTC
Labels: needs investigation
