### ISSUE TITLE
Unable to create store view and website after installing the module

### ISSUE THREAD

**Issue by szreka** [amzn/amazon-payments-magento-2-plugin#184] opened 2018-01-26 16:01 UTC
#### What I expected

After trying to create a new store view in the admin panel, I was expecting it to  be created. Same with the website.

#### What happened instead

I got an error message of `Requested store is not found` after trying to create the store view, and an error message of `No such entity` after trying to create a website.

#### Steps to reproduce the issue

1. Installing the Amazon Payments module via composer
2. Run `setup:upgrade`
3. Login into the admin panel
4. Go to Stores => All Stores
5. Click 'Create Store View'
6. Enter some content in the fields and click 'Save Store View'
7. The error of `Requested store is not found` is shown and no store view is added.

I'm definitely sure this module is causing it, as when it's been removed, everything got back to normal. When added back, this issue occurred again.
This is the same issue with another module: https://github.com/magento/magento2/issues/12405

#### Your setup

* Magento version: 2.2.2
* Magento Edition: Enterprise

**Comment by islandskater43** [comment] 2018-01-27 20:03
Confirmed on Magento 2.2.2 CE. Extension version 1.2.4.

**Comment by foolsworld** [comment] 2018-01-29 02:52
Experience the same/similar issue. Magento 2.2.2 community clean install. 

Installed the latest version of Amazon Pay. After installation I am not able to create a new "website" in magento admin. Error message "no such entity" in an attempt to save the new website.

I started the setup from scratch with a clean magento install to make sure there are no compatibility issues with other extensions etc.

I am surprised that not more people are reporting this issue?

Thanks for looking into this issue!

**Comment by islandskater43** [comment] 2018-01-29 04:23
Thanks @foolsworld and @szreka, we're looking into this.

**Comment by gbear** [comment] 2018-01-29 18:57
Related: #185

**Comment by foolsworld** [comment] 2018-02-05 18:22
Hi, guys

Is there any development on this issue. I cannot believe that there are not more people who are trying to us Amazon Pay, are trying to run a multi website setup and are not experiencing the same issue.

Thanks again for looking into this!

**Comment by islandskater43** [comment] 2018-02-06 07:43
@foolsworld - we're working on a fix right now. Should be merged soon.

**Comment by islandskater43** [comment] 2018-02-14 17:06
Received additional feedback on the fix (https://github.com/amzn/amazon-payments-magento-2-plugin/commit/a038abc2877497348e99688c6f25c99f78ee19bf#r27552652). Need to make a minor adjustment. Reopening and will address shortly.

**Closed** 2018-02-15 13:06 UTC
Labels: ack, reproducible

**Comment by danielneu** [comment] 2018-02-15 13:08
PR was merged, QA for new release due today

**Comment by foolsworld** [comment] 2018-02-24 06:39
Hi Daniel,

I would like to confirm that a new Amazon Pay extension for Magento 2 has been released. What is the latest stable version? Where can I find the latest version for download? Has the problem of not being able to create a new “website” be resolved with the new update?

Thanks for the info and kind regards,
Stephan

**Comment by danielneu** [comment] 2018-02-26 11:23
Hi @foolsworld 

our releases can be found here: https://github.com/amzn/amazon-payments-magento-2-plugin/releases

This issue is part of the latest release. Installation instructions are in the guide, which we link to from our repository landing page.

The release on Magento marketplace might be always a bit delayed, due to Magento processing times. 

Please let us know, if this is still not working for you with the latest version.

Best wishes 
Daniel
