### ISSUE TITLE
Amazon Pay does not create order in M2 Backend while payment is receives by amazon

### ISSUE THREAD

**Issue by andidhouse** [amzn/amazon-payments-magento-2-plugin#191] opened 2018-02-06 14:14 UTC
We have some orders which are not shown in the magento 2 backend - but the customers respond to us that they have payed via amazon pay.

If we look in our amazon pay account the transaction is there - but in our magento2 system there is no order with the order number.

Somehow the amazon pay extension does not send the order back to magento2 - worst cast of course as the customer has payed but no order could be shipped out.

**Comment by islandskater43** [comment] 2018-02-06 17:23
@andidhouse - are there any relevant log files you could share for this issue? Amazon Pay specific log files and generic Magento exception log files would be very beneficial.

**Comment by islandskater43** [comment] 2018-02-10 07:07
@andidhouse - any possibility of sharing the above mentioned info?

**Comment by daniel-ness** [comment] 2018-07-19 11:40
I'm also experiencing this issue. It has only happened two times, both this month.

IPN logs appear fine and resemble any other order. Within the exception log I have identified this error:

`[2018-07-16 10:55:02] main.ERROR: Amazon\Core\Exception\AmazonServiceUnavailableException: Amazon Pay could not process your request. Please try again. in xxxxxxxxxxxxxxxx/releases/20180628093802/vendor/amzn/amazon-payments-magento-2-plugin/src/Payment/Domain/AbstractAmazonAuthorizationResponse.php:4`

**Comment by prayagr** [comment] 2018-07-20 16:54
Hi @daniel-ness , which Magento and Amazon Pay versions are you using? I think your issue maybe related to #193

**Comment by daniel-ness** [comment] 2018-07-24 13:06
Hi @prayagr 

It's Magento v2.1.11 with Amazon Pay v1.2.6

**Comment by lemked** [comment] 2019-07-12 07:30
Hi @daniel-ness ,

I'm sorry for the late reply on this issue. I believe this should not occur anymore with more recent versions of our extension. Can you verify and confirm this?

Kind regards,
Daniel

**Comment by Axel29** [comment] 2019-09-20 13:26
Hi,

I'm experiencing the same problem.

Two customers reported that they paid (which is true as we can see in the Amazon Pay's seller central) but the order isn't present at all in Magento.

The common factor between those two customers is that they failed their first order and then succeeded. I don't know if that's the cause of the bug since there doesn't seem to be any log anywhere.

Magento version: 2.3.0
AmazonPay's version: 3.0.0
PHP version: 7.2
MySQL version: 5.7

Did anyone find a way to identify this bug / fix it?

Thank you,

Axel

**Comment by scgoeswild** [comment] 2020-01-10 06:09
Hello to everyone,
I have out same issue.
The customers place the orders on m2, the transaction on amz pay works correctly but the order is not placed while the payments is OK.

I tried to update on the latest version of the extension but the problem persist.

Magento version: 2.2.0
AmazonPay's version: 3.0.0
PHP version: 7.1
MySQL version: 5.7

Anyone has experienced this issue?

**Comment by christianzichichi** [comment] 2020-01-10 14:10
Hi @Axel29,

please follow these instructions to update our extension to the latest available version we have a patch for (Amazon Pay version 3.3.0), Magento version 2.3.0:

https://gist.github.com/christianzichichi/934438b59a0894b68fdb79f56a98dd00

Can you verify the issue does not occur anymore after?

Thanks
Regards,

Christian

**Comment by christianzichichi** [comment] 2020-01-10 14:19
Hi @scgoeswild,

can you please provide merchant details like merchant Id, orderIds and Amazon Pay logs at payments-cp-devel@amazon.com?

Moreover, can you please also share the update process you followed to install version 3.0.0? I think you installed a wrong version since for Magento 2.1.0 to 2.2.3 versions, the latest available AP version is 1.3.0 (branch 1.x of this repo: https://github.com/amzn/amazon-payments-magento-2-plugin/tree/1.x). We also suggest upgrading your Magento installation to a more recent one.

Thank you
Regards

Christian

**Comment by christianzichichi** [comment] 2020-01-27 16:36
Hi all,

As we noticed no further inputs here I am going to have to go ahead and close this issue for now. If you experience any further issues please provide any screenshots or logs to payments-cp-devel@amazon.com, we would be glad to help you troubleshoot further. At this point, we would also recommend you upgrading your magento installation to the latest version to get the latest version of our extension too.

Thanks
Regards

Christian

**Closed by christianzichichi** 2020-01-27 16:36 UTC
Labels: ack, customer feedback required

**Comment by pavitrapapiofficial** [comment] 2021-07-02 04:48
Hi,
I am facing the same issue on Magento Version : 2.3.5 Plugin Version : 3.4.1. Orders not being created in M2 admin but payment is successful.
Additionally, I have got an error <Code>OrderReferenceNotModifiable</Code>
`[2021-06-25 17:08:58] amazonClientLogger.DEBUG: POST
mws.amazonservices.com
/OffAmazonPayments/2013-01-01
AWSAccessKeyId=ACCESS_KEY_OF_MY_ACCOUNT&Action=SetOrderReferenceDetails&AmazonOrderReferenceId=P01-0714261-7849312&OrderReferenceAttributes.OrderTotal.Amount=63.2&OrderReferenceAttributes.OrderTotal.CurrencyCode=USD&OrderReferenceAttributes.PlatformId=AUGT0HMCLQVX1&OrderReferenceAttributes.SellerOrderAttributes.CustomInformation=Magento%20Version%20%3A%202.3.5%20Plugin%20Version%20%3A%203.4.1&OrderReferenceAttributes.SellerOrderAttributes.StoreName=STOERE_NAME&SellerId=SELLER_ID&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-06-25T17%3A08%3A58.000Z&Version=2013-01-01 [] []
[2021-06-25 17:08:59] amazonClientLogger.DEBUG: amazon-pay-sdk-php/3.7.1 (PHP/7.3.28; Linux/x86_64/3.10.0-1160.21.1.el7.x86_64) [] []
[2021-06-25 17:08:59] amazonClientLogger.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>OrderReferenceNotModifiable</Code>
  </Error>
  <RequestId>a5bdf99b-76c8-45a4-aac8-419547116f02</RequestId>
</ErrorResponse>
 [] []`

I hope this info will help you
