### ISSUE TITLE
OrderReferenceID invalid

### ISSUE THREAD

**Issue by clickdigitalinteractive** [amzn/amazon-payments-magento-2-plugin#66] opened 2017-05-30 22:36 UTC
#### What I expected

Pay with amazon from cart view. 

#### What happened instead

when checkout page loads, error message displays in the amazon payment box: We're sorry, but there's a problem processing your payment from this website. Please contact the seller for assistance.

Amazon logs say:
<Code>InvalidOrderReferenceId</Code>
    <Message>The OrderReferenceId S00-0000000-0000000 is invalid.</Message>

#### Steps to reproduce the issue

this is testing in sandbox. checking out.

#### Your setup

* Magento version: 2.1.3
* Magento Edition: Community 

* JavaScript Console: 
Widgets.js?nomin:43 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at Object.c.Button (https://static-na.payments-amazon.com/OffAmazonPayments/us/sandbox/js/Widgets.js?nomin:43:132940)
    at $.(anonymous function).(anonymous function)._renderAmazonButton (url/en_US/Amazon_Payment/js/amazon-button.js:100:31)
    at $.(anonymous function).(anonymous function)._renderAmazonButton (url/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._create (url/en_US/Amazon_Payment/js/amazon-button.js:44:19)
    at $.(anonymous function).(anonymous function)._create (url/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._createWidget (url/en_US/jquery/jquery-ui.js:561:8)
    at new $.(anonymous function).(anonymous function) (url/en_US/jquery/jquery-ui.js:363:9)
    at $.(anonymous function).(anonymous function) (url/en_US/jquery/jquery-ui.js:357:11)
    at url/en_US/mage/apply/main.js:30:17
    at Object.execCb (url/en_US/requirejs/require.js:1650:33)
    at Object.context.execCb (url/en_US/mage/requirejs/resolver.js:131:31)
    at Module.check (url/en_US/requirejs/require.js:866:51)
    at Module.<anonymous> (url/en_US/requirejs/require.js:1113:34)
    at url/en_US/requirejs/require.js:132:23
    at url/en_US/requirejs/require.js:1156:21
    at each (url/en_US/requirejs/require.js:57:31)
c.Button @ Widgets.js?nomin:43
_renderAmazonButton @ amazon-button.js:100
(anonymous) @ jquery-ui.js:402
_create @ amazon-button.js:44
(anonymous) @ jquery-ui.js:402
_createWidget @ jquery-ui.js:561
$.(anonymous function).(anonymous function) @ jquery-ui.js:363
$.(anonymous function).(anonymous function) @ jquery-ui.js:357
(anonymous) @ main.js:30
execCb @ require.js:1650
context.execCb @ resolver.js:131
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
callGetModule @ require.js:1170
completeLoad @ require.js:1544
onScriptLoad @ require.js:1671

Amazon logs error:
[2017-05-30 22:22:48] main.DEBUG: POST
mws.amazonservices.com
/OffAmazonPayments_Sandbox/2013-01-01
AWSAccessKeyId=**REMOVINGTHISFORTHISPOST**&Action=GetOrderReferenceDetails&AmazonOrderReferenceId=S00-0000000-0000000&SellerId=*REMOVINGTHISFORTHISPOST**&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2017-05-30T22%3A22%3A48.000Z&Version=2013-01-01 {"is_exception":false} []
[2017-05-30 22:22:48] main.DEBUG: / (Language=PHP/7.0.19; Platform=Linux/x86_64/2.6.32-642.6.2.el6.x86_64; MWSClientVersion=2.1.0) {"is_exception":false} []
[2017-05-30 22:22:48] main.DEBUG: <ErrorResponse xmlns="http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidOrderReferenceId</Code>
    <Message>The OrderReferenceId S00-0000000-0000000 is invalid.</Message>
  </Error>
  <RequestId>a8236811-6dd1-49a0-b22a-d3f18a483389</RequestId>
</ErrorResponse>
 {"is_exception":false} []

**Comment by danielneu** [comment] 2017-06-02 09:56
Hi,

you can ignore the error:

InvalidOrderReferenceId
The OrderReferenceId S00-0000000-0000000 is invalid.

This is an API call which fails by design to verify your credentials.

The issue you are facing has to have a different cause. Are you able to share a staging site we could have a look at?

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-06-15 09:17
Hi,

are you still experiencing issues or can this be resolved?

Best wishes 
Daniel

**Comment by danielneu** [comment] 2017-06-21 12:32
Closing this due to missing feedback and no one else experiencing a similar issue.

**Closed by danielneu** 2017-06-21 12:32 UTC
Labels: customer feedback required, needs investigation

**Comment by kilis** [comment] 2017-08-30 14:29
I have kind of the same issue:
http://prntscr.com/geyle9
http://prntscr.com/geylz5

**Comment by danielneu** [comment] 2017-08-31 11:25
Hi @kilis 

can you share steps to reproduce and when this happens the output of amazonStorage.getOrderReference() ?

**Comment by kilis** [comment] 2017-08-31 12:30
Hey, @danielneu 
To be honest simple workflow.
1. Add Amazon pay creds to M2 BE
2. Enable play with amazon pay
3. Add product to cart and go to Checkout with amazon pay button

We have a custom theme in our project but it fails there with an error. When our theme is switched off to Lluma it kind of works but still has a loader icon in shipping method (width rendered shipping widget in amazon). (Login with amazon works in both of them.)

Main problem is that it is hard to debug where the problem is located. And it can only be debugged on server side not locally. Still even statck trace in js console cannot help.

I need a better way to debug the problem. Have you any suggestion?

**Comment by danielneu** [comment] 2017-08-31 14:47
Hi,

can you check if this helps with your custom theme?

https://github.com/amzn/amazon-payments-magento-2-plugin/issues/10#issuecomment-267435966

Best wishes 
Daniel

**Comment by kilis** [comment] 2017-08-31 14:49
We use scss

ceturtd., 2017. g. 31. aug. plkst. 17:47 — Daniel Neu <
notifications@github.com> rakstīja:

**Comment by kilis** [comment] 2017-08-31 14:51
Also all m2 less is removed. Theme is from scratch

ceturtd., 2017. g. 31. aug. plkst. 17:47 — Daniel Neu <
notifications@github.com> rakstīja:

**Comment by danielneu** [comment] 2017-08-31 14:55
@kilis 

I want to have our experts check this.
Your issue is however different to the original, which is why I don't want to open up this issue again.

Can you create a fresh one? I will then loop in our experts.

Thanks
Daniel

**Comment by kilis** [comment] 2017-08-31 15:18
We have a staging server that is almost clean. I will check there. It just simply hard to debbug.
Also if we need your expert where should we write to? To get answers ASAP.

**Comment by danielneu** [comment] 2017-08-31 16:35
Hi,

once you create a fresh issue for this, I will loop them in.
They will most likely need staging access to reproduce and investigate. you can share those details with me by sending them over to: payments-cp-devel@amazon.com

Thanks
Daniel

**Comment by tejashp77** [comment] 2017-09-08 04:53
Issue related to the ticket. any solution?
https://drive.google.com/file/d/0B7niKZFI3BV4cnZZMGpVOS1GZ2s/view?usp=drivesdk

**Comment by kilis** [comment] 2017-09-08 05:22
For us not

**Comment by ProsperaTeam** [comment] 2017-09-08 07:42
Hi.. Is this issue resolved? If yes what was the solution? 
I'm trying java sdk of amamzon pay and getting same error for authorization API. Any solutions?

**Comment by danielneu** [comment] 2017-09-08 08:42
Hi,

the initially reported ticket was about:

InvalidOrderReferenceId
The OrderReferenceId S00-0000000-0000000 is invalid.

This is **not** an issue, please ignore this.

For any other issue, which is still happening, or open, please created a dedicated issue with detailed information.

**Comment by danielneu** [comment] 2017-09-08 08:45
Please also make sure to use the newest version (1.1.4). We changed a lot in this area which could resolve this.

**Comment by kilis** [comment] 2017-09-08 08:49
Thanks! Will check ASAP and inform about results

**Comment by nscreed** [comment] 2017-11-21 04:41
I have fixed the issue. I was set the fronted widget environment to Live but mistakenly the backed it was set to sandbox. So, the order was not place to amazon end and the error was throwing.
