### ISSUE TITLE
Pay By Amazon extension not displaying in Internet Explorer 

### ISSUE THREAD

**Issue by EmilyPepperman** [amzn/amazon-payments-magento-2-plugin#13] opened 2016-12-06 14:40 UTC
We need to test other versions of Internet Explorer... but in IE 11 no one is able to checkout with Pay By Amazon extension. The iframe isn't displaying ... it is fine in other browsers. Anyone see this issue as well?

**Comment by danielneu** [comment] 2016-12-08 10:39
This was caused by usage of Promise, which is not known to IE11, replaced it with jQuery deferred.
Fixed in version 1.0.8

**Closed by danielneu** 2016-12-08 10:39 UTC
Labels: bug
